# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changeLabelName.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_changeLabelName(object):
    def setupUi(self, changeLabelName):
        changeLabelName.setObjectName("changeLabelName")
        changeLabelName.resize(640, 480)
        self.textEditLabel1 = QtWidgets.QTextEdit(changeLabelName)
        self.textEditLabel1.setGeometry(QtCore.QRect(240, 40, 201, 61))
        self.textEditLabel1.setObjectName("textEditLabel1")
        self.textEditLabel2 = QtWidgets.QTextEdit(changeLabelName)
        self.textEditLabel2.setGeometry(QtCore.QRect(240, 140, 201, 61))
        self.textEditLabel2.setObjectName("textEditLabel2")
        self.textEditLabel3 = QtWidgets.QTextEdit(changeLabelName)
        self.textEditLabel3.setGeometry(QtCore.QRect(240, 230, 201, 61))
        self.textEditLabel3.setObjectName("textEditLabel3")
        self.label = QtWidgets.QLabel(changeLabelName)
        self.label.setGeometry(QtCore.QRect(140, 60, 67, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(changeLabelName)
        self.label_2.setGeometry(QtCore.QRect(140, 160, 67, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(changeLabelName)
        self.label_3.setGeometry(QtCore.QRect(140, 250, 67, 19))
        self.label_3.setObjectName("label_3")
        self.updateNameButton = QtWidgets.QPushButton(changeLabelName)
        self.updateNameButton.setGeometry(QtCore.QRect(280, 330, 100, 31))
        self.updateNameButton.setObjectName("updateNameButton")

        self.retranslateUi(changeLabelName)
        QtCore.QMetaObject.connectSlotsByName(changeLabelName)

    def retranslateUi(self, changeLabelName):
        _translate = QtCore.QCoreApplication.translate
        changeLabelName.setWindowTitle(_translate("changeLabelName", "Form"))
        self.label.setText(_translate("changeLabelName", "Label -1"))
        self.label_2.setText(_translate("changeLabelName", "Label -2"))
        self.label_3.setText(_translate("changeLabelName", "Label -3"))
        self.updateNameButton.setText(_translate("changeLabelName", "Update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    changeLabelName = QtWidgets.QWidget()
    ui = Ui_changeLabelName()
    ui.setupUi(changeLabelName)
    changeLabelName.show()
    sys.exit(app.exec_())
