# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'historyDetailsOfData.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_historydetailsofdata(object):
    def setupUi(self, historydetailsofdata):
        historydetailsofdata.setObjectName("historydetailsofdata")
        historydetailsofdata.resize(601, 484)
        self.gridLayout = QtWidgets.QGridLayout(historydetailsofdata)
        self.gridLayout.setObjectName("gridLayout")
        self.historyhVerticalLayout = QtWidgets.QVBoxLayout()
        self.historyhVerticalLayout.setObjectName("historyhVerticalLayout")
        self.gridLayout.addLayout(self.historyhVerticalLayout, 0, 0, 1, 1)

        self.retranslateUi(historydetailsofdata)
        QtCore.QMetaObject.connectSlotsByName(historydetailsofdata)

    def retranslateUi(self, historydetailsofdata):
        _translate = QtCore.QCoreApplication.translate
        historydetailsofdata.setWindowTitle(_translate("historydetailsofdata", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    historydetailsofdata = QtWidgets.QWidget()
    ui = Ui_historydetailsofdata()
    ui.setupUi(historydetailsofdata)
    historydetailsofdata.show()
    sys.exit(app.exec_())
