# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_ras.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(2036, 1365)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(2036, 1365))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QMainWindow{background-color:black;}")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.time_label = QtWidgets.QLabel(self.centralWidget)
        self.time_label.setGeometry(QtCore.QRect(210, 13, 41, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_label.sizePolicy().hasHeightForWidth())
        self.time_label.setSizePolicy(sizePolicy)
        self.time_label.setMinimumSize(QtCore.QSize(41, 20))
        self.time_label.setMaximumSize(QtCore.QSize(41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.time_label.setFont(font)
        self.time_label.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.time_label.setObjectName("time_label")
        self.elapsedTimeLabel = QtWidgets.QLabel(self.centralWidget)
        self.elapsedTimeLabel.setGeometry(QtCore.QRect(730, 13, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elapsedTimeLabel.sizePolicy().hasHeightForWidth())
        self.elapsedTimeLabel.setSizePolicy(sizePolicy)
        self.elapsedTimeLabel.setMinimumSize(QtCore.QSize(100, 20))
        self.elapsedTimeLabel.setMaximumSize(QtCore.QSize(41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.elapsedTimeLabel.setFont(font)
        self.elapsedTimeLabel.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.elapsedTimeLabel.setObjectName("elapsedTimeLabel")
        self.anaesthesiaTimeLabel = QtWidgets.QLabel(self.centralWidget)
        self.anaesthesiaTimeLabel.setGeometry(QtCore.QRect(1430, 13, 141, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anaesthesiaTimeLabel.sizePolicy().hasHeightForWidth())
        self.anaesthesiaTimeLabel.setSizePolicy(sizePolicy)
        self.anaesthesiaTimeLabel.setMinimumSize(QtCore.QSize(141, 20))
        self.anaesthesiaTimeLabel.setMaximumSize(QtCore.QSize(41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.anaesthesiaTimeLabel.setFont(font)
        self.anaesthesiaTimeLabel.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.anaesthesiaTimeLabel.setObjectName("anaesthesiaTimeLabel")
        self.time_show = QtWidgets.QLabel(self.centralWidget)
        self.time_show.setGeometry(QtCore.QRect(21, 16, 600, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_show.sizePolicy().hasHeightForWidth())
        self.time_show.setSizePolicy(sizePolicy)
        self.time_show.setMinimumSize(QtCore.QSize(600, 150))
        font = QtGui.QFont()
        font.setPointSize(72)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.time_show.setFont(font)
        self.time_show.setStyleSheet("QLabel { color: #FFFFFF; \n"
"                  font-size:72pt;\n"
"                  font-weight:600;}")
        self.time_show.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.time_show.setWordWrap(True)
        self.time_show.setObjectName("time_show")
        self.lcd1 = QtWidgets.QLabel(self.centralWidget)
        self.lcd1.setGeometry(QtCore.QRect(668, 16, 600, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd1.sizePolicy().hasHeightForWidth())
        self.lcd1.setSizePolicy(sizePolicy)
        self.lcd1.setMinimumSize(QtCore.QSize(600, 150))
        self.lcd1.setStyleSheet("QLabel { color: #FFFFFF; \n"
"                  font-size:72pt; }")
        self.lcd1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lcd1.setObjectName("lcd1")
        self.displayArea = QtWidgets.QLabel(self.centralWidget)
        self.displayArea.setGeometry(QtCore.QRect(1310, 16, 600, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayArea.sizePolicy().hasHeightForWidth())
        self.displayArea.setSizePolicy(sizePolicy)
        self.displayArea.setMinimumSize(QtCore.QSize(600, 150))
        font = QtGui.QFont()
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.displayArea.setFont(font)
        self.displayArea.setStyleSheet("QLabel { color: #FFFF00; \n"
"                  font-size:72pt;\n"
"                  font-weight:600;}")
        self.displayArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.displayArea.setObjectName("displayArea")
        self.setTimeSetting = QtWidgets.QToolButton(self.centralWidget)
        self.setTimeSetting.setGeometry(QtCore.QRect(33, 200, 41, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setTimeSetting.sizePolicy().hasHeightForWidth())
        self.setTimeSetting.setSizePolicy(sizePolicy)
        self.setTimeSetting.setMinimumSize(QtCore.QSize(41, 42))
        self.setTimeSetting.setMaximumSize(QtCore.QSize(42, 42))
        self.setTimeSetting.setStyleSheet("QToolButton#setTimeSetting{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#setTimeSetting:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/settings-clock-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setTimeSetting.setIcon(icon)
        self.setTimeSetting.setIconSize(QtCore.QSize(23, 23))
        self.setTimeSetting.setObjectName("setTimeSetting")
        self.day_date_show = QtWidgets.QLabel(self.centralWidget)
        self.day_date_show.setGeometry(QtCore.QRect(88, 200, 371, 33))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.day_date_show.sizePolicy().hasHeightForWidth())
        self.day_date_show.setSizePolicy(sizePolicy)
        self.day_date_show.setMinimumSize(QtCore.QSize(351, 31))
        self.day_date_show.setStyleSheet("QLabel { color: #FFFFFF; \n"
"                  font-size:20pt;\n"
"                  font-weight:600;}")
        self.day_date_show.setObjectName("day_date_show")
        self.start = QtWidgets.QToolButton(self.centralWidget)
        self.start.setGeometry(QtCore.QRect(788, 200, 42, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start.sizePolicy().hasHeightForWidth())
        self.start.setSizePolicy(sizePolicy)
        self.start.setMinimumSize(QtCore.QSize(42, 42))
        self.start.setMaximumSize(QtCore.QSize(42, 42))
        self.start.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/play_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start.setIcon(icon1)
        self.start.setObjectName("start")
        self.reset = QtWidgets.QToolButton(self.centralWidget)
        self.reset.setGeometry(QtCore.QRect(844, 200, 42, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset.sizePolicy().hasHeightForWidth())
        self.reset.setSizePolicy(sizePolicy)
        self.reset.setMinimumSize(QtCore.QSize(42, 42))
        self.reset.setMaximumSize(QtCore.QSize(42, 42))
        self.reset.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reset.setIcon(icon2)
        self.reset.setIconSize(QtCore.QSize(21, 21))
        self.reset.setObjectName("reset")
        self.addAdditonalChronosButton = QtWidgets.QToolButton(self.centralWidget)
        self.addAdditonalChronosButton.setGeometry(QtCore.QRect(900, 200, 147, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addAdditonalChronosButton.sizePolicy().hasHeightForWidth())
        self.addAdditonalChronosButton.setSizePolicy(sizePolicy)
        self.addAdditonalChronosButton.setMinimumSize(QtCore.QSize(141, 42))
        self.addAdditonalChronosButton.setMaximumSize(QtCore.QSize(147, 42))
        self.addAdditonalChronosButton.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.addAdditonalChronosButton.setIconSize(QtCore.QSize(21, 21))
        self.addAdditonalChronosButton.setObjectName("addAdditonalChronosButton")
        self.timerSet = QtWidgets.QToolButton(self.centralWidget)
        self.timerSet.setGeometry(QtCore.QRect(1448, 200, 42, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timerSet.sizePolicy().hasHeightForWidth())
        self.timerSet.setSizePolicy(sizePolicy)
        self.timerSet.setMinimumSize(QtCore.QSize(42, 42))
        self.timerSet.setMaximumSize(QtCore.QSize(42, 42))
        self.timerSet.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/time-settings-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.timerSet.setIcon(icon3)
        self.timerSet.setIconSize(QtCore.QSize(34, 34))
        self.timerSet.setObjectName("timerSet")
        self.startButton = QtWidgets.QToolButton(self.centralWidget)
        self.startButton.setGeometry(QtCore.QRect(1504, 200, 42, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMinimumSize(QtCore.QSize(42, 42))
        self.startButton.setMaximumSize(QtCore.QSize(42, 42))
        self.startButton.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.startButton.setIcon(icon1)
        self.startButton.setObjectName("startButton")
        self.resetButton = QtWidgets.QToolButton(self.centralWidget)
        self.resetButton.setGeometry(QtCore.QRect(1560, 200, 42, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetButton.sizePolicy().hasHeightForWidth())
        self.resetButton.setSizePolicy(sizePolicy)
        self.resetButton.setMinimumSize(QtCore.QSize(42, 42))
        self.resetButton.setMaximumSize(QtCore.QSize(42, 42))
        self.resetButton.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.resetButton.setIcon(icon2)
        self.resetButton.setIconSize(QtCore.QSize(21, 21))
        self.resetButton.setObjectName("resetButton")
        self.tempLabelName = QtWidgets.QLabel(self.centralWidget)
        self.tempLabelName.setGeometry(QtCore.QRect(1470, 290, 91, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempLabelName.sizePolicy().hasHeightForWidth())
        self.tempLabelName.setSizePolicy(sizePolicy)
        self.tempLabelName.setMinimumSize(QtCore.QSize(91, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tempLabelName.setFont(font)
        self.tempLabelName.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.tempLabelName.setObjectName("tempLabelName")
        self.humidityLabelName = QtWidgets.QLabel(self.centralWidget)
        self.humidityLabelName.setGeometry(QtCore.QRect(1721, 290, 67, 19))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.humidityLabelName.sizePolicy().hasHeightForWidth())
        self.humidityLabelName.setSizePolicy(sizePolicy)
        self.humidityLabelName.setMinimumSize(QtCore.QSize(67, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.humidityLabelName.setFont(font)
        self.humidityLabelName.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.humidityLabelName.setObjectName("humidityLabelName")
        self.otLighteningDetails = QtWidgets.QToolButton(self.centralWidget)
        self.otLighteningDetails.setGeometry(QtCore.QRect(11, 280, 199, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otLighteningDetails.sizePolicy().hasHeightForWidth())
        self.otLighteningDetails.setSizePolicy(sizePolicy)
        self.otLighteningDetails.setMinimumSize(QtCore.QSize(196, 42))
        self.otLighteningDetails.setMaximumSize(QtCore.QSize(199, 42))
        self.otLighteningDetails.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/lighting_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.otLighteningDetails.setIcon(icon4)
        self.otLighteningDetails.setCheckable(False)
        self.otLighteningDetails.setAutoRepeat(False)
        self.otLighteningDetails.setAutoExclusive(False)
        self.otLighteningDetails.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.otLighteningDetails.setObjectName("otLighteningDetails")
        self.centralwidget = QtWidgets.QWidget(self.centralWidget)
        self.centralwidget.setGeometry(QtCore.QRect(230, 310, 1111, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1111, 500))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.tempIcon = QtWidgets.QLabel(self.centralWidget)
        self.tempIcon.setGeometry(QtCore.QRect(1410, 342, 61, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempIcon.sizePolicy().hasHeightForWidth())
        self.tempIcon.setSizePolicy(sizePolicy)
        self.tempIcon.setMinimumSize(QtCore.QSize(61, 60))
        self.tempIcon.setMaximumSize(QtCore.QSize(61, 60))
        self.tempIcon.setText("")
        self.tempIcon.setPixmap(QtGui.QPixmap("icon/thermometer_white.png"))
        self.tempIcon.setScaledContents(True)
        self.tempIcon.setObjectName("tempIcon")
        self.tempShow = QtWidgets.QLabel(self.centralWidget)
        self.tempShow.setGeometry(QtCore.QRect(1496, 337, 171, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempShow.sizePolicy().hasHeightForWidth())
        self.tempShow.setSizePolicy(sizePolicy)
        self.tempShow.setMinimumSize(QtCore.QSize(121, 70))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.tempShow.setFont(font)
        self.tempShow.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.tempShow.setObjectName("tempShow")
        self.humidityIcon = QtWidgets.QLabel(self.centralWidget)
        self.humidityIcon.setGeometry(QtCore.QRect(1700, 342, 51, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.humidityIcon.sizePolicy().hasHeightForWidth())
        self.humidityIcon.setSizePolicy(sizePolicy)
        self.humidityIcon.setMinimumSize(QtCore.QSize(51, 60))
        self.humidityIcon.setMaximumSize(QtCore.QSize(51, 60))
        self.humidityIcon.setText("")
        self.humidityIcon.setPixmap(QtGui.QPixmap("icon/humidity_60_60.png"))
        self.humidityIcon.setScaledContents(True)
        self.humidityIcon.setObjectName("humidityIcon")
        self.humidityShow = QtWidgets.QLabel(self.centralWidget)
        self.humidityShow.setGeometry(QtCore.QRect(1780, 337, 171, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.humidityShow.sizePolicy().hasHeightForWidth())
        self.humidityShow.setSizePolicy(sizePolicy)
        self.humidityShow.setMinimumSize(QtCore.QSize(151, 70))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.humidityShow.setFont(font)
        self.humidityShow.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.humidityShow.setObjectName("humidityShow")
        self.ventiLationDetails = QtWidgets.QToolButton(self.centralWidget)
        self.ventiLationDetails.setGeometry(QtCore.QRect(11, 336, 199, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ventiLationDetails.sizePolicy().hasHeightForWidth())
        self.ventiLationDetails.setSizePolicy(sizePolicy)
        self.ventiLationDetails.setMinimumSize(QtCore.QSize(196, 42))
        self.ventiLationDetails.setMaximumSize(QtCore.QSize(199, 42))
        self.ventiLationDetails.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/fan_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ventiLationDetails.setIcon(icon5)
        self.ventiLationDetails.setCheckable(False)
        self.ventiLationDetails.setAutoRepeat(False)
        self.ventiLationDetails.setAutoExclusive(False)
        self.ventiLationDetails.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.ventiLationDetails.setObjectName("ventiLationDetails")
        self.gasIndicator = QtWidgets.QToolButton(self.centralWidget)
        self.gasIndicator.setGeometry(QtCore.QRect(11, 392, 199, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gasIndicator.sizePolicy().hasHeightForWidth())
        self.gasIndicator.setSizePolicy(sizePolicy)
        self.gasIndicator.setMinimumSize(QtCore.QSize(196, 42))
        self.gasIndicator.setMaximumSize(QtCore.QSize(199, 42))
        self.gasIndicator.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/pressure_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gasIndicator.setIcon(icon6)
        self.gasIndicator.setCheckable(False)
        self.gasIndicator.setAutoRepeat(False)
        self.gasIndicator.setAutoExclusive(False)
        self.gasIndicator.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.gasIndicator.setObjectName("gasIndicator")
        self.tempSetLabel = QtWidgets.QLabel(self.centralWidget)
        self.tempSetLabel.setGeometry(QtCore.QRect(1473, 415, 31, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempSetLabel.sizePolicy().hasHeightForWidth())
        self.tempSetLabel.setSizePolicy(sizePolicy)
        self.tempSetLabel.setMinimumSize(QtCore.QSize(31, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tempSetLabel.setFont(font)
        self.tempSetLabel.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.tempSetLabel.setObjectName("tempSetLabel")
        self.humiditySetLabel = QtWidgets.QLabel(self.centralWidget)
        self.humiditySetLabel.setGeometry(QtCore.QRect(1766, 415, 31, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.humiditySetLabel.sizePolicy().hasHeightForWidth())
        self.humiditySetLabel.setSizePolicy(sizePolicy)
        self.humiditySetLabel.setMinimumSize(QtCore.QSize(31, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.humiditySetLabel.setFont(font)
        self.humiditySetLabel.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.humiditySetLabel.setObjectName("humiditySetLabel")
        self.tempSetShow = QtWidgets.QLabel(self.centralWidget)
        self.tempSetShow.setGeometry(QtCore.QRect(1473, 451, 41, 39))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempSetShow.sizePolicy().hasHeightForWidth())
        self.tempSetShow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.tempSetShow.setFont(font)
        self.tempSetShow.setScaledContents(True)
        self.tempSetShow.setObjectName("tempSetShow")
        self.humiditySetShow = QtWidgets.QLabel(self.centralWidget)
        self.humiditySetShow.setGeometry(QtCore.QRect(1748, 451, 41, 39))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.humiditySetShow.sizePolicy().hasHeightForWidth())
        self.humiditySetShow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.humiditySetShow.setFont(font)
        self.humiditySetShow.setScaledContents(True)
        self.humiditySetShow.setObjectName("humiditySetShow")
        self.historyDetails = QtWidgets.QToolButton(self.centralWidget)
        self.historyDetails.setGeometry(QtCore.QRect(11, 448, 199, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.historyDetails.sizePolicy().hasHeightForWidth())
        self.historyDetails.setSizePolicy(sizePolicy)
        self.historyDetails.setMinimumSize(QtCore.QSize(196, 42))
        self.historyDetails.setMaximumSize(QtCore.QSize(199, 42))
        self.historyDetails.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icon/report_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.historyDetails.setIcon(icon7)
        self.historyDetails.setCheckable(False)
        self.historyDetails.setAutoRepeat(False)
        self.historyDetails.setAutoExclusive(False)
        self.historyDetails.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.historyDetails.setObjectName("historyDetails")
        self.downTemperatureButton = QtWidgets.QToolButton(self.centralWidget)
        self.downTemperatureButton.setGeometry(QtCore.QRect(1453, 506, 42, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downTemperatureButton.sizePolicy().hasHeightForWidth())
        self.downTemperatureButton.setSizePolicy(sizePolicy)
        self.downTemperatureButton.setMinimumSize(QtCore.QSize(42, 42))
        self.downTemperatureButton.setMaximumSize(QtCore.QSize(42, 42))
        self.downTemperatureButton.setStyleSheet("QToolButton#downTemperatureButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton#downTemperatureButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icon/down-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downTemperatureButton.setIcon(icon8)
        self.downTemperatureButton.setObjectName("downTemperatureButton")
        self.upTemperatureButton = QtWidgets.QToolButton(self.centralWidget)
        self.upTemperatureButton.setGeometry(QtCore.QRect(1515, 506, 42, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upTemperatureButton.sizePolicy().hasHeightForWidth())
        self.upTemperatureButton.setSizePolicy(sizePolicy)
        self.upTemperatureButton.setMinimumSize(QtCore.QSize(42, 42))
        self.upTemperatureButton.setMaximumSize(QtCore.QSize(42, 42))
        self.upTemperatureButton.setStyleSheet("QToolButton#upTemperatureButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton#upTemperatureButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icon/up-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upTemperatureButton.setIcon(icon9)
        self.upTemperatureButton.setObjectName("upTemperatureButton")
        self.downHumidityButton = QtWidgets.QToolButton(self.centralWidget)
        self.downHumidityButton.setGeometry(QtCore.QRect(1725, 506, 42, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downHumidityButton.sizePolicy().hasHeightForWidth())
        self.downHumidityButton.setSizePolicy(sizePolicy)
        self.downHumidityButton.setMinimumSize(QtCore.QSize(42, 42))
        self.downHumidityButton.setMaximumSize(QtCore.QSize(42, 42))
        self.downHumidityButton.setStyleSheet("QToolButton#downHumidityButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton#downHumidityButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.downHumidityButton.setIcon(icon8)
        self.downHumidityButton.setObjectName("downHumidityButton")
        self.upHumidityButton = QtWidgets.QToolButton(self.centralWidget)
        self.upHumidityButton.setGeometry(QtCore.QRect(1788, 506, 42, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upHumidityButton.sizePolicy().hasHeightForWidth())
        self.upHumidityButton.setSizePolicy(sizePolicy)
        self.upHumidityButton.setMinimumSize(QtCore.QSize(42, 42))
        self.upHumidityButton.setMaximumSize(QtCore.QSize(42, 42))
        self.upHumidityButton.setStyleSheet("QToolButton#upHumidityButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton#upHumidityButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.upHumidityButton.setIcon(icon9)
        self.upHumidityButton.setObjectName("upHumidityButton")
        self.multiMediaDetails = QtWidgets.QToolButton(self.centralWidget)
        self.multiMediaDetails.setGeometry(QtCore.QRect(11, 504, 199, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.multiMediaDetails.sizePolicy().hasHeightForWidth())
        self.multiMediaDetails.setSizePolicy(sizePolicy)
        self.multiMediaDetails.setMinimumSize(QtCore.QSize(196, 42))
        self.multiMediaDetails.setMaximumSize(QtCore.QSize(199, 42))
        self.multiMediaDetails.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icon/multimedia_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.multiMediaDetails.setIcon(icon10)
        self.multiMediaDetails.setCheckable(False)
        self.multiMediaDetails.setAutoRepeat(False)
        self.multiMediaDetails.setAutoExclusive(False)
        self.multiMediaDetails.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.multiMediaDetails.setObjectName("multiMediaDetails")
        self.temeratureGraph = QtWidgets.QToolButton(self.centralWidget)
        self.temeratureGraph.setGeometry(QtCore.QRect(1451, 564, 109, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temeratureGraph.sizePolicy().hasHeightForWidth())
        self.temeratureGraph.setSizePolicy(sizePolicy)
        self.temeratureGraph.setMinimumSize(QtCore.QSize(106, 41))
        self.temeratureGraph.setMaximumSize(QtCore.QSize(109, 41))
        self.temeratureGraph.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icon/temp_graph.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.temeratureGraph.setIcon(icon11)
        self.temeratureGraph.setIconSize(QtCore.QSize(24, 24))
        self.temeratureGraph.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.temeratureGraph.setObjectName("temeratureGraph")
        self.humidityGraph = QtWidgets.QToolButton(self.centralWidget)
        self.humidityGraph.setGeometry(QtCore.QRect(1723, 564, 109, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.humidityGraph.sizePolicy().hasHeightForWidth())
        self.humidityGraph.setSizePolicy(sizePolicy)
        self.humidityGraph.setMinimumSize(QtCore.QSize(106, 41))
        self.humidityGraph.setMaximumSize(QtCore.QSize(109, 41))
        self.humidityGraph.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icon/humidity_graph.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.humidityGraph.setIcon(icon12)
        self.humidityGraph.setIconSize(QtCore.QSize(24, 24))
        self.humidityGraph.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.humidityGraph.setObjectName("humidityGraph")
        self.differentialLabel = QtWidgets.QLabel(self.centralWidget)
        self.differentialLabel.setGeometry(QtCore.QRect(1446, 630, 141, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.differentialLabel.sizePolicy().hasHeightForWidth())
        self.differentialLabel.setSizePolicy(sizePolicy)
        self.differentialLabel.setMinimumSize(QtCore.QSize(141, 20))
        self.differentialLabel.setMaximumSize(QtCore.QSize(141, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.differentialLabel.setFont(font)
        self.differentialLabel.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.differentialLabel.setObjectName("differentialLabel")
        self.hepaLabel = QtWidgets.QLabel(self.centralWidget)
        self.hepaLabel.setGeometry(QtCore.QRect(1731, 632, 131, 19))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hepaLabel.sizePolicy().hasHeightForWidth())
        self.hepaLabel.setSizePolicy(sizePolicy)
        self.hepaLabel.setMinimumSize(QtCore.QSize(131, 19))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hepaLabel.setFont(font)
        self.hepaLabel.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.hepaLabel.setObjectName("hepaLabel")
        self.differentialPressureShow = QtWidgets.QLabel(self.centralWidget)
        self.differentialPressureShow.setGeometry(QtCore.QRect(1460, 668, 191, 77))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.differentialPressureShow.sizePolicy().hasHeightForWidth())
        self.differentialPressureShow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.differentialPressureShow.setFont(font)
        self.differentialPressureShow.setScaledContents(True)
        self.differentialPressureShow.setObjectName("differentialPressureShow")
        self.hepaFilterStatus = QtWidgets.QLabel(self.centralWidget)
        self.hepaFilterStatus.setGeometry(QtCore.QRect(1710, 668, 181, 77))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hepaFilterStatus.sizePolicy().hasHeightForWidth())
        self.hepaFilterStatus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.hepaFilterStatus.setFont(font)
        self.hepaFilterStatus.setScaledContents(True)
        self.hepaFilterStatus.setObjectName("hepaFilterStatus")
        self.logoDisplay = QtWidgets.QLabel(self.centralWidget)
        self.logoDisplay.setGeometry(QtCore.QRect(12, 960, 91, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoDisplay.sizePolicy().hasHeightForWidth())
        self.logoDisplay.setSizePolicy(sizePolicy)
        self.logoDisplay.setMinimumSize(QtCore.QSize(91, 61))
        self.logoDisplay.setMaximumSize(QtCore.QSize(91, 61))
        self.logoDisplay.setScaledContents(True)
        self.logoDisplay.setObjectName("logoDisplay")
        self.toolButton_9 = QtWidgets.QToolButton(self.centralWidget)
        self.toolButton_9.setGeometry(QtCore.QRect(1510, 988, 42, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_9.sizePolicy().hasHeightForWidth())
        self.toolButton_9.setSizePolicy(sizePolicy)
        self.toolButton_9.setMinimumSize(QtCore.QSize(42, 42))
        self.toolButton_9.setMaximumSize(QtCore.QSize(42, 42))
        self.toolButton_9.setStyleSheet("QToolButton#toolButton_9{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#toolButton_9:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.toolButton_9.setObjectName("toolButton_9")
        self.phoneCallingButton = QtWidgets.QToolButton(self.centralWidget)
        self.phoneCallingButton.setEnabled(True)
        self.phoneCallingButton.setGeometry(QtCore.QRect(1560, 988, 42, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phoneCallingButton.sizePolicy().hasHeightForWidth())
        self.phoneCallingButton.setSizePolicy(sizePolicy)
        self.phoneCallingButton.setMinimumSize(QtCore.QSize(42, 42))
        self.phoneCallingButton.setMaximumSize(QtCore.QSize(42, 42))
        self.phoneCallingButton.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icon/phone-call-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.phoneCallingButton.setIcon(icon13)
        self.phoneCallingButton.setIconSize(QtCore.QSize(44, 44))
        self.phoneCallingButton.setObjectName("phoneCallingButton")
        self.powerButton = QtWidgets.QToolButton(self.centralWidget)
        self.powerButton.setGeometry(QtCore.QRect(1607, 988, 121, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.powerButton.sizePolicy().hasHeightForWidth())
        self.powerButton.setSizePolicy(sizePolicy)
        self.powerButton.setMinimumSize(QtCore.QSize(121, 42))
        self.powerButton.setMaximumSize(QtCore.QSize(121, 42))
        self.powerButton.setStyleSheet("QToolButton#powerButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#powerButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icon/power_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.powerButton.setIcon(icon14)
        self.powerButton.setObjectName("powerButton")
        self.settingsButton = QtWidgets.QToolButton(self.centralWidget)
        self.settingsButton.setGeometry(QtCore.QRect(1740, 988, 42, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsButton.sizePolicy().hasHeightForWidth())
        self.settingsButton.setSizePolicy(sizePolicy)
        self.settingsButton.setMinimumSize(QtCore.QSize(42, 42))
        self.settingsButton.setMaximumSize(QtCore.QSize(42, 42))
        self.settingsButton.setStyleSheet("QToolButton#settingsButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#settingsButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("icon/settings_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsButton.setIcon(icon15)
        self.settingsButton.setIconSize(QtCore.QSize(24, 24))
        self.settingsButton.setObjectName("settingsButton")
        self.homeButton = QtWidgets.QToolButton(self.centralWidget)
        self.homeButton.setGeometry(QtCore.QRect(1790, 988, 42, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homeButton.sizePolicy().hasHeightForWidth())
        self.homeButton.setSizePolicy(sizePolicy)
        self.homeButton.setMinimumSize(QtCore.QSize(42, 42))
        self.homeButton.setMaximumSize(QtCore.QSize(42, 42))
        self.homeButton.setStyleSheet("QToolButton#homeButton{\n"
"    border-style: outset;\n"
"    border-width:1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#homeButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("icon/home_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeButton.setIcon(icon16)
        self.homeButton.setIconSize(QtCore.QSize(24, 24))
        self.homeButton.setObjectName("homeButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(261, 930, 1071, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.medicalGasLabelTitle = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.medicalGasLabelTitle.sizePolicy().hasHeightForWidth())
        self.medicalGasLabelTitle.setSizePolicy(sizePolicy)
        self.medicalGasLabelTitle.setMinimumSize(QtCore.QSize(101, 21))
        self.medicalGasLabelTitle.setMaximumSize(QtCore.QSize(719, 21))
        self.medicalGasLabelTitle.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.medicalGasLabelTitle.setObjectName("medicalGasLabelTitle")
        self.gridLayout.addWidget(self.medicalGasLabelTitle, 0, 0, 1, 1)
        self.nitrousOxide = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nitrousOxide.sizePolicy().hasHeightForWidth())
        self.nitrousOxide.setSizePolicy(sizePolicy)
        self.nitrousOxide.setMinimumSize(QtCore.QSize(100, 42))
        self.nitrousOxide.setStyleSheet("QToolButton#nitrousOxide{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#nitrousOxide:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.nitrousOxide.setObjectName("nitrousOxide")
        self.gridLayout.addWidget(self.nitrousOxide, 1, 0, 1, 1)
        self.air = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.air.sizePolicy().hasHeightForWidth())
        self.air.setSizePolicy(sizePolicy)
        self.air.setMinimumSize(QtCore.QSize(100, 42))
        self.air.setStyleSheet("QToolButton#air{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#air:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.air.setObjectName("air")
        self.gridLayout.addWidget(self.air, 1, 1, 1, 1)
        self.air7 = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.air7.sizePolicy().hasHeightForWidth())
        self.air7.setSizePolicy(sizePolicy)
        self.air7.setMinimumSize(QtCore.QSize(100, 42))
        self.air7.setStyleSheet("QToolButton#air7{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#air7:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.air7.setObjectName("air7")
        self.gridLayout.addWidget(self.air7, 1, 2, 1, 1)
        self.cabonDiOxide = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cabonDiOxide.sizePolicy().hasHeightForWidth())
        self.cabonDiOxide.setSizePolicy(sizePolicy)
        self.cabonDiOxide.setMinimumSize(QtCore.QSize(100, 42))
        self.cabonDiOxide.setStyleSheet("QToolButton#cabonDiOxide{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#cabonDiOxide:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.cabonDiOxide.setObjectName("cabonDiOxide")
        self.gridLayout.addWidget(self.cabonDiOxide, 1, 3, 1, 1)
        self.oxygen = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oxygen.sizePolicy().hasHeightForWidth())
        self.oxygen.setSizePolicy(sizePolicy)
        self.oxygen.setMinimumSize(QtCore.QSize(100, 42))
        self.oxygen.setStyleSheet("QToolButton#oxygen{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#oxygen:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.oxygen.setObjectName("oxygen")
        self.gridLayout.addWidget(self.oxygen, 1, 4, 1, 1)
        self.vacuum = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vacuum.sizePolicy().hasHeightForWidth())
        self.vacuum.setSizePolicy(sizePolicy)
        self.vacuum.setMinimumSize(QtCore.QSize(100, 42))
        self.vacuum.setStyleSheet("QToolButton#vacuum{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#vacuum:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.vacuum.setObjectName("vacuum")
        self.gridLayout.addWidget(self.vacuum, 1, 5, 1, 1)
        self.ips = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ips.sizePolicy().hasHeightForWidth())
        self.ips.setSizePolicy(sizePolicy)
        self.ips.setMinimumSize(QtCore.QSize(100, 42))
        self.ips.setStyleSheet("QToolButton#ips{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#ips:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.ips.setObjectName("ips")
        self.gridLayout.addWidget(self.ips, 1, 6, 1, 1)
        self.menuTitleName = QtWidgets.QLabel(self.centralWidget)
        self.menuTitleName.setGeometry(QtCore.QRect(750, 280, 141, 20))
        self.menuTitleName.setWordWrap(True)
        self.menuTitleName.setObjectName("menuTitleName")
        self.leftMenuTitleLine = QtWidgets.QLabel(self.centralWidget)
        self.leftMenuTitleLine.setGeometry(QtCore.QRect(230, 290, 503, 3))
        self.leftMenuTitleLine.setStyleSheet("QLabel{ \n"
"    background-color: #000000; \n"
"}\n"
"  ")
        self.leftMenuTitleLine.setText("")
        self.leftMenuTitleLine.setObjectName("leftMenuTitleLine")
        self.rightMenuTitleLine = QtWidgets.QLabel(self.centralWidget)
        self.rightMenuTitleLine.setGeometry(QtCore.QRect(900, 290, 445, 3))
        self.rightMenuTitleLine.setStyleSheet("QLabel{ \n"
"    background-color: #000000; \n"
"}\n"
"  ")
        self.rightMenuTitleLine.setText("")
        self.rightMenuTitleLine.setObjectName("rightMenuTitleLine")
        self.hepa = QtWidgets.QToolButton(self.centralWidget)
        self.hepa.setGeometry(QtCore.QRect(1700, 810, 148, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hepa.sizePolicy().hasHeightForWidth())
        self.hepa.setSizePolicy(sizePolicy)
        self.hepa.setMinimumSize(QtCore.QSize(100, 42))
        self.hepa.setStyleSheet("QToolButton#hepa{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#hepa:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.hepa.setObjectName("hepa")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.time_label.setText(_translate("MainWindow", "Time"))
        self.elapsedTimeLabel.setText(_translate("MainWindow", "Elapsed Time"))
        self.anaesthesiaTimeLabel.setText(_translate("MainWindow", "Anaesthesia  Time"))
        self.time_show.setText(_translate("MainWindow", "<html><head/><body><p>00:00:00</p></body></html>"))
        self.lcd1.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:72pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"justify\" style=\"vertical-align: text-top ; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:`0; text-indent:0px;\">00:00:00</p></body></html>"))
        self.displayArea.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:72pt; font-weight:600; color:#ffa400;\">00:00:00</span></p></body></html>"))
        self.setTimeSetting.setText(_translate("MainWindow", "Set Time"))
        self.day_date_show.setText(_translate("MainWindow", "Date Show"))
        self.start.setText(_translate("MainWindow", "Play and Pause"))
        self.reset.setText(_translate("MainWindow", "Reset"))
        self.addAdditonalChronosButton.setText(_translate("MainWindow", "Additional Chronos"))
        self.timerSet.setText(_translate("MainWindow", "Set"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.tempLabelName.setText(_translate("MainWindow", "Temperature"))
        self.humidityLabelName.setText(_translate("MainWindow", " Humidity"))
        self.otLighteningDetails.setText(_translate("MainWindow", "          Lightening"))
        self.tempShow.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt;\">15.3</span></p></body></html>"))
        self.humidityShow.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">64.0</span></p></body></html>"))
        self.ventiLationDetails.setText(_translate("MainWindow", "           Ventilation"))
        self.gasIndicator.setText(_translate("MainWindow", "           Gas"))
        self.tempSetLabel.setText(_translate("MainWindow", "Set"))
        self.humiditySetLabel.setText(_translate("MainWindow", "Set"))
        self.tempSetShow.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">00</p></body></html>"))
        self.humiditySetShow.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">00</p></body></html>"))
        self.historyDetails.setText(_translate("MainWindow", "           History"))
        self.downTemperatureButton.setText(_translate("MainWindow", "Down"))
        self.upTemperatureButton.setText(_translate("MainWindow", "Up"))
        self.downHumidityButton.setText(_translate("MainWindow", "Down"))
        self.upHumidityButton.setText(_translate("MainWindow", "Up"))
        self.multiMediaDetails.setText(_translate("MainWindow", "           Multimedia"))
        self.temeratureGraph.setText(_translate("MainWindow", "GRAPH"))
        self.humidityGraph.setText(_translate("MainWindow", "GRAPH"))
        self.differentialLabel.setText(_translate("MainWindow", "Diffrential Pressure"))
        self.hepaLabel.setText(_translate("MainWindow", "Hepa Filter Status"))
        self.differentialPressureShow.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">90</p></body></html>"))
        self.hepaFilterStatus.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">95%</p></body></html>"))
        self.logoDisplay.setText(_translate("MainWindow", "Logo Display"))
        self.toolButton_9.setText(_translate("MainWindow", "..."))
        self.phoneCallingButton.setText(_translate("MainWindow", "..."))
        self.powerButton.setText(_translate("MainWindow", "STANDBY/CLEAN"))
        self.settingsButton.setText(_translate("MainWindow", "Settings"))
        self.homeButton.setText(_translate("MainWindow", "..."))
        self.medicalGasLabelTitle.setText(_translate("MainWindow", "Medical Gas"))
        self.nitrousOxide.setText(_translate("MainWindow", "N2O"))
        self.air.setText(_translate("MainWindow", "AIR"))
        self.air7.setText(_translate("MainWindow", "AIR7"))
        self.cabonDiOxide.setText(_translate("MainWindow", "CO2"))
        self.oxygen.setText(_translate("MainWindow", "O2"))
        self.vacuum.setText(_translate("MainWindow", "VAC"))
        self.ips.setText(_translate("MainWindow", "IPS"))
        self.menuTitleName.setText(_translate("MainWindow", "Title H"))
        self.hepa.setText(_translate("MainWindow", "Hepa"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
