# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1467, 904)
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QMainWindow{background-color:black;}")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.elapsedTimeLabel = QtWidgets.QLabel(self.centralWidget)
        self.elapsedTimeLabel.setGeometry(QtCore.QRect(620, 0, 101, 19))
        self.elapsedTimeLabel.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.elapsedTimeLabel.setObjectName("elapsedTimeLabel")
        self.setTimeSetting = QtWidgets.QToolButton(self.centralWidget)
        self.setTimeSetting.setGeometry(QtCore.QRect(10, 140, 91, 41))
        self.setTimeSetting.setStyleSheet("QToolButton#setTimeSetting{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#setTimeSetting:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.setTimeSetting.setObjectName("setTimeSetting")
        self.toolButton_9 = QtWidgets.QToolButton(self.centralWidget)
        self.toolButton_9.setGeometry(QtCore.QRect(980, 710, 27, 29))
        self.toolButton_9.setStyleSheet("QToolButton#toolButton_9{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#toolButton_9:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.toolButton_9.setObjectName("toolButton_9")
        self.phoneCallingButton = QtWidgets.QToolButton(self.centralWidget)
        self.phoneCallingButton.setEnabled(True)
        self.phoneCallingButton.setGeometry(QtCore.QRect(1020, 700, 41, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phoneCallingButton.sizePolicy().hasHeightForWidth())
        self.phoneCallingButton.setSizePolicy(sizePolicy)
        self.phoneCallingButton.setStyleSheet("QToolButton#toolButton_10{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#toolButton_10:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/phone-call-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.phoneCallingButton.setIcon(icon)
        self.phoneCallingButton.setIconSize(QtCore.QSize(44, 44))
        self.phoneCallingButton.setObjectName("phoneCallingButton")
        self.powerButton = QtWidgets.QToolButton(self.centralWidget)
        self.powerButton.setGeometry(QtCore.QRect(1070, 710, 121, 31))
        self.powerButton.setStyleSheet("QToolButton#powerButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#powerButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/power_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.powerButton.setIcon(icon1)
        self.powerButton.setObjectName("powerButton")
        self.downTemperatureButton = QtWidgets.QToolButton(self.centralWidget)
        self.downTemperatureButton.setGeometry(QtCore.QRect(985, 380, 41, 40))
        self.downTemperatureButton.setStyleSheet("QToolButton#downTemperatureButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton#downTemperatureButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/down-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downTemperatureButton.setIcon(icon2)
        self.downTemperatureButton.setObjectName("downTemperatureButton")
        self.upTemperatureButton = QtWidgets.QToolButton(self.centralWidget)
        self.upTemperatureButton.setGeometry(QtCore.QRect(1050, 380, 41, 40))
        self.upTemperatureButton.setStyleSheet("QToolButton#upTemperatureButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton#upTemperatureButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/up-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upTemperatureButton.setIcon(icon3)
        self.upTemperatureButton.setObjectName("upTemperatureButton")
        self.downHumidityButton = QtWidgets.QToolButton(self.centralWidget)
        self.downHumidityButton.setGeometry(QtCore.QRect(1198, 380, 41, 40))
        self.downHumidityButton.setStyleSheet("QToolButton#downHumidityButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton#downHumidityButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.downHumidityButton.setIcon(icon2)
        self.downHumidityButton.setObjectName("downHumidityButton")
        self.upHumidityButton = QtWidgets.QToolButton(self.centralWidget)
        self.upHumidityButton.setGeometry(QtCore.QRect(1259, 380, 41, 40))
        self.upHumidityButton.setStyleSheet("QToolButton#upHumidityButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton#upHumidityButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.upHumidityButton.setIcon(icon3)
        self.upHumidityButton.setObjectName("upHumidityButton")
        self.humidityLabelName = QtWidgets.QLabel(self.centralWidget)
        self.humidityLabelName.setGeometry(QtCore.QRect(1215, 210, 67, 18))
        self.humidityLabelName.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.humidityLabelName.setObjectName("humidityLabelName")
        self.tempIcon = QtWidgets.QLabel(self.centralWidget)
        self.tempIcon.setGeometry(QtCore.QRect(925, 250, 61, 60))
        self.tempIcon.setText("")
        self.tempIcon.setPixmap(QtGui.QPixmap("icon/thermometer_white.png"))
        self.tempIcon.setScaledContents(True)
        self.tempIcon.setObjectName("tempIcon")
        self.humidityIcon = QtWidgets.QLabel(self.centralWidget)
        self.humidityIcon.setGeometry(QtCore.QRect(1155, 250, 51, 60))
        self.humidityIcon.setText("")
        self.humidityIcon.setPixmap(QtGui.QPixmap("icon/humidity_60_60.png"))
        self.humidityIcon.setScaledContents(True)
        self.humidityIcon.setObjectName("humidityIcon")
        self.tempLabelName = QtWidgets.QLabel(self.centralWidget)
        self.tempLabelName.setGeometry(QtCore.QRect(995, 210, 91, 20))
        self.tempLabelName.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.tempLabelName.setObjectName("tempLabelName")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 290, 222, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.otLighteningDetails = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.otLighteningDetails.setStyleSheet("QPushButton#otLighteningDetails {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QPushButton#otLighteningDetails:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/lighting_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.otLighteningDetails.setIcon(icon4)
        self.otLighteningDetails.setIconSize(QtCore.QSize(19, 19))
        self.otLighteningDetails.setObjectName("otLighteningDetails")
        self.verticalLayout.addWidget(self.otLighteningDetails)
        self.ventiLationDetails = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ventiLationDetails.setStyleSheet("QPushButton#ventiLationDetails {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QPushButton#ventiLationDetails:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/fan_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ventiLationDetails.setIcon(icon5)
        self.ventiLationDetails.setIconSize(QtCore.QSize(19, 19))
        self.ventiLationDetails.setObjectName("ventiLationDetails")
        self.verticalLayout.addWidget(self.ventiLationDetails)
        self.gasIndicator = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.gasIndicator.setEnabled(True)
        self.gasIndicator.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gasIndicator.setStyleSheet("QPushButton#gasIndicator{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QPushButton#gasIndicator:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/pressure_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gasIndicator.setIcon(icon6)
        self.gasIndicator.setIconSize(QtCore.QSize(19, 19))
        self.gasIndicator.setObjectName("gasIndicator")
        self.verticalLayout.addWidget(self.gasIndicator)
        self.historyDetails = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.historyDetails.setStyleSheet("QPushButton#historyDetails{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QPushButton#historyDetails:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icon/report_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.historyDetails.setIcon(icon7)
        self.historyDetails.setIconSize(QtCore.QSize(19, 19))
        self.historyDetails.setObjectName("historyDetails")
        self.verticalLayout.addWidget(self.historyDetails)
        self.multiMediaDetails = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.multiMediaDetails.setStyleSheet("QPushButton#multiMediaDetails{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QPushButton#multiMediaDetails:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icon/multimedia_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.multiMediaDetails.setIcon(icon8)
        self.multiMediaDetails.setIconSize(QtCore.QSize(19, 19))
        self.multiMediaDetails.setObjectName("multiMediaDetails")
        self.verticalLayout.addWidget(self.multiMediaDetails)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(280, 700, 671, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.nitrousOxide = QtWidgets.QToolButton(self.horizontalLayoutWidget_2)
        self.nitrousOxide.setStyleSheet("QToolButton#nitrousOxide{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#nitrousOxide:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.nitrousOxide.setObjectName("nitrousOxide")
        self.horizontalLayout_3.addWidget(self.nitrousOxide)
        self.air = QtWidgets.QToolButton(self.horizontalLayoutWidget_2)
        self.air.setStyleSheet("QToolButton#air{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#air:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.air.setObjectName("air")
        self.horizontalLayout_3.addWidget(self.air)
        self.air7 = QtWidgets.QToolButton(self.horizontalLayoutWidget_2)
        self.air7.setStyleSheet("QToolButton#air7{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#air7:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.air7.setObjectName("air7")
        self.horizontalLayout_3.addWidget(self.air7)
        self.cabonDiOxide = QtWidgets.QToolButton(self.horizontalLayoutWidget_2)
        self.cabonDiOxide.setStyleSheet("QToolButton#cabonDiOxide{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#cabonDiOxide:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.cabonDiOxide.setObjectName("cabonDiOxide")
        self.horizontalLayout_3.addWidget(self.cabonDiOxide)
        self.oxygen = QtWidgets.QToolButton(self.horizontalLayoutWidget_2)
        self.oxygen.setStyleSheet("QToolButton#oxygen{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#oxygen:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.oxygen.setObjectName("oxygen")
        self.horizontalLayout_3.addWidget(self.oxygen)
        self.vacuum = QtWidgets.QToolButton(self.horizontalLayoutWidget_2)
        self.vacuum.setStyleSheet("QToolButton#vacuum{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#vacuum:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.vacuum.setObjectName("vacuum")
        self.horizontalLayout_3.addWidget(self.vacuum)
        self.ips = QtWidgets.QToolButton(self.horizontalLayoutWidget_2)
        self.ips.setStyleSheet("QToolButton#ips{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#ips:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.ips.setObjectName("ips")
        self.horizontalLayout_3.addWidget(self.ips)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(1205, 700, 110, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.settingsButton = QtWidgets.QToolButton(self.horizontalLayoutWidget_4)
        self.settingsButton.setStyleSheet("QToolButton#settingsButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#settingsButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icon/settings_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsButton.setIcon(icon9)
        self.settingsButton.setIconSize(QtCore.QSize(24, 24))
        self.settingsButton.setObjectName("settingsButton")
        self.horizontalLayout_8.addWidget(self.settingsButton)
        self.homeButton = QtWidgets.QToolButton(self.horizontalLayoutWidget_4)
        self.homeButton.setStyleSheet("QToolButton#homeButton{\n"
"    border-style: outset;\n"
"    border-width:1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#homeButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icon/home_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeButton.setIcon(icon10)
        self.homeButton.setIconSize(QtCore.QSize(24, 24))
        self.homeButton.setObjectName("homeButton")
        self.horizontalLayout_8.addWidget(self.homeButton)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(480, 140, 371, 51))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.reset = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.reset.setStyleSheet("QPushButton#reset {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QPushButton#reset:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.reset.setObjectName("reset")
        self.horizontalLayout_10.addWidget(self.reset)
        self.start = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.start.setStyleSheet("QPushButton#start {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QPushButton#start:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.start.setObjectName("start")
        self.horizontalLayout_10.addWidget(self.start)
        self.addAdditonalChronosButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.addAdditonalChronosButton.setStyleSheet("QPushButton#addAdditonalChronoButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QPushButton#addAdditonalChronoButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.addAdditonalChronosButton.setObjectName("addAdditonalChronosButton")
        self.horizontalLayout_10.addWidget(self.addAdditonalChronosButton)
        self.day_date_show = QtWidgets.QLabel(self.centralWidget)
        self.day_date_show.setGeometry(QtCore.QRect(130, 140, 321, 31))
        self.day_date_show.setStyleSheet("QLabel { color: #FFFFFF; \n"
"                  font-size:20pt;\n"
"                  font-weight:600;}")
        self.day_date_show.setObjectName("day_date_show")
        self.centralwidget = QtWidgets.QWidget(self.centralWidget)
        self.centralwidget.setGeometry(QtCore.QRect(260, 220, 641, 451))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.time_label = QtWidgets.QLabel(self.centralWidget)
        self.time_label.setGeometry(QtCore.QRect(160, -1, 41, 20))
        self.time_label.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.time_label.setObjectName("time_label")
        self.anaesthesiaTimeLabel = QtWidgets.QLabel(self.centralWidget)
        self.anaesthesiaTimeLabel.setGeometry(QtCore.QRect(1065, 0, 141, 21))
        self.anaesthesiaTimeLabel.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.anaesthesiaTimeLabel.setObjectName("anaesthesiaTimeLabel")
        self.temeratureGraph = QtWidgets.QPushButton(self.centralWidget)
        self.temeratureGraph.setGeometry(QtCore.QRect(985, 430, 106, 39))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.temeratureGraph.setFont(font)
        self.temeratureGraph.setStyleSheet("QPushButton#temeratureGraph {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QPushButton#temeratureGraph:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icon/temp_graph.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.temeratureGraph.setIcon(icon11)
        self.temeratureGraph.setIconSize(QtCore.QSize(24, 24))
        self.temeratureGraph.setObjectName("temeratureGraph")
        self.humidityGraph = QtWidgets.QPushButton(self.centralWidget)
        self.humidityGraph.setGeometry(QtCore.QRect(1195, 430, 106, 39))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.humidityGraph.setFont(font)
        self.humidityGraph.setStyleSheet("QPushButton#humidityGraph {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QPushButton#humidityGraph:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icon/humidity_graph.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.humidityGraph.setIcon(icon12)
        self.humidityGraph.setIconSize(QtCore.QSize(24, 24))
        self.humidityGraph.setObjectName("humidityGraph")
        self.tempShow = QtWidgets.QLabel(self.centralWidget)
        self.tempShow.setGeometry(QtCore.QRect(995, 240, 121, 70))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.tempShow.setFont(font)
        self.tempShow.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.tempShow.setObjectName("tempShow")
        self.humidityShow = QtWidgets.QLabel(self.centralWidget)
        self.humidityShow.setGeometry(QtCore.QRect(1215, 240, 151, 70))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.humidityShow.setFont(font)
        self.humidityShow.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.humidityShow.setObjectName("humidityShow")
        self.tempSetLabel = QtWidgets.QLabel(self.centralWidget)
        self.tempSetLabel.setGeometry(QtCore.QRect(1015, 320, 31, 20))
        self.tempSetLabel.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.tempSetLabel.setObjectName("tempSetLabel")
        self.humiditySetLabel = QtWidgets.QLabel(self.centralWidget)
        self.humiditySetLabel.setGeometry(QtCore.QRect(1235, 320, 31, 20))
        self.humiditySetLabel.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.humiditySetLabel.setObjectName("humiditySetLabel")
        self.tempSetShow = QtWidgets.QLabel(self.centralWidget)
        self.tempSetShow.setGeometry(QtCore.QRect(1015, 340, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.tempSetShow.setFont(font)
        self.tempSetShow.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.tempSetShow.setObjectName("tempSetShow")
        self.humiditySetShow = QtWidgets.QLabel(self.centralWidget)
        self.humiditySetShow.setGeometry(QtCore.QRect(1225, 340, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.humiditySetShow.setFont(font)
        self.humiditySetShow.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.humiditySetShow.setObjectName("humiditySetShow")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(925, 560, 61, 60))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("../../.designer/backup/icon/compressor.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(1145, 560, 51, 60))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("../../.designer/backup/icon/air-filter-white.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.differentialLabel = QtWidgets.QLabel(self.centralWidget)
        self.differentialLabel.setGeometry(QtCore.QRect(975, 520, 141, 20))
        self.differentialLabel.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.differentialLabel.setObjectName("differentialLabel")
        self.hepaLabel = QtWidgets.QLabel(self.centralWidget)
        self.hepaLabel.setGeometry(QtCore.QRect(1185, 520, 131, 19))
        self.hepaLabel.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.hepaLabel.setObjectName("hepaLabel")
        self.hepaFilterStatus = QtWidgets.QLabel(self.centralWidget)
        self.hepaFilterStatus.setGeometry(QtCore.QRect(1215, 560, 131, 70))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.hepaFilterStatus.setFont(font)
        self.hepaFilterStatus.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.hepaFilterStatus.setObjectName("hepaFilterStatus")
        self.differentialPressureShow = QtWidgets.QLabel(self.centralWidget)
        self.differentialPressureShow.setGeometry(QtCore.QRect(1025, 550, 91, 70))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.differentialPressureShow.setFont(font)
        self.differentialPressureShow.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.differentialPressureShow.setObjectName("differentialPressureShow")
        self.lcd1 = QtWidgets.QLabel(self.centralWidget)
        self.lcd1.setGeometry(QtCore.QRect(470, 20, 411, 111))
        self.lcd1.setStyleSheet("QLabel { color: #FFFFFF; \n"
"                  font-size:72pt;\n"
"                  font-weight:600;}")
        self.lcd1.setObjectName("lcd1")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(1010, 140, 291, 51))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.timerSet = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.timerSet.setStyleSheet("QPushButton#timerSet {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QPushButton#timerSet:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.timerSet.setObjectName("timerSet")
        self.horizontalLayout_5.addWidget(self.timerSet)
        self.startButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.startButton.setStyleSheet("QPushButton#startButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QPushButton#startButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_5.addWidget(self.startButton)
        self.resetButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.resetButton.setStyleSheet("QPushButton#resetButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QPushButton#resetButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_5.addWidget(self.resetButton)
        self.displayArea = QtWidgets.QLabel(self.centralWidget)
        self.displayArea.setGeometry(QtCore.QRect(930, 20, 421, 101))
        font = QtGui.QFont()
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.displayArea.setFont(font)
        self.displayArea.setStyleSheet("QLabel { color: #FFFF00; \n"
"                  font-size:72pt;\n"
"                  font-weight:600;}")
        self.displayArea.setObjectName("displayArea")
        self.layoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 620, 221, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnOn = QtWidgets.QPushButton(self.layoutWidget)
        self.btnOn.setStyleSheet("QPushButton#btnOn{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px; \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QPushButton#btnOn:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.btnOn.setObjectName("btnOn")
        self.horizontalLayout.addWidget(self.btnOn)
        self.btnOff = QtWidgets.QPushButton(self.layoutWidget)
        self.btnOff.setStyleSheet("QPushButton#btnOff{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px; \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QPushButton#btnOff:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.btnOff.setObjectName("btnOff")
        self.horizontalLayout.addWidget(self.btnOff)
        self.medicalGasLabelTitle = QtWidgets.QLabel(self.centralWidget)
        self.medicalGasLabelTitle.setGeometry(QtCore.QRect(320, 670, 101, 21))
        self.medicalGasLabelTitle.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.medicalGasLabelTitle.setObjectName("medicalGasLabelTitle")
        self.logoDisplay = QtWidgets.QLabel(self.centralWidget)
        self.logoDisplay.setGeometry(QtCore.QRect(20, 680, 81, 61))
        self.logoDisplay.setScaledContents(True)
        self.logoDisplay.setObjectName("logoDisplay")
        self.time_show = QtWidgets.QLabel(self.centralWidget)
        self.time_show.setGeometry(QtCore.QRect(1, 21, 421, 116))
        font = QtGui.QFont()
        font.setPointSize(72)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.time_show.setFont(font)
        self.time_show.setStyleSheet("QLabel { color: #FFFFFF; \n"
"                  font-size:72pt;\n"
"                  font-weight:600;}")
        self.time_show.setObjectName("time_show")
        self.menuTitleName = QtWidgets.QLabel(self.centralWidget)
        self.menuTitleName.setGeometry(QtCore.QRect(430, 200, 67, 19))
        self.menuTitleName.setObjectName("menuTitleName")
        self.leftMenuTitleLine = QtWidgets.QLabel(self.centralWidget)
        self.leftMenuTitleLine.setGeometry(QtCore.QRect(310, 190, 67, 19))
        self.leftMenuTitleLine.setObjectName("leftMenuTitleLine")
        self.rightMenuTitleLine = QtWidgets.QLabel(self.centralWidget)
        self.rightMenuTitleLine.setGeometry(QtCore.QRect(600, 200, 67, 19))
        self.rightMenuTitleLine.setObjectName("rightMenuTitleLine")
        self.hepa = QtWidgets.QToolButton(self.centralWidget)
        self.hepa.setGeometry(QtCore.QRect(1230, 640, 51, 35))
        self.hepa.setStyleSheet("QToolButton#hepa{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#hepa:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.hepa.setObjectName("hepa")
        self.speakerButton = QtWidgets.QToolButton(self.centralWidget)
        self.speakerButton.setGeometry(QtCore.QRect(229, 701, 42, 42))
        self.speakerButton.setStyleSheet("QToolButton#speakerButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#speakerButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icon/speaker-on-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.speakerButton.setIcon(icon13)
        self.speakerButton.setIconSize(QtCore.QSize(42, 42))
        self.speakerButton.setObjectName("speakerButton")
        self.time_show.raise_()
        self.elapsedTimeLabel.raise_()
        self.setTimeSetting.raise_()
        self.toolButton_9.raise_()
        self.phoneCallingButton.raise_()
        self.powerButton.raise_()
        self.downHumidityButton.raise_()
        self.upHumidityButton.raise_()
        self.humidityLabelName.raise_()
        self.tempIcon.raise_()
        self.humidityIcon.raise_()
        self.tempLabelName.raise_()
        self.verticalLayoutWidget.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.horizontalLayoutWidget_4.raise_()
        self.horizontalLayoutWidget_5.raise_()
        self.day_date_show.raise_()
        self.centralwidget.raise_()
        self.time_label.raise_()
        self.anaesthesiaTimeLabel.raise_()
        self.temeratureGraph.raise_()
        self.humidityGraph.raise_()
        self.tempShow.raise_()
        self.humidityShow.raise_()
        self.tempSetLabel.raise_()
        self.humiditySetLabel.raise_()
        self.tempSetShow.raise_()
        self.humiditySetShow.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.differentialLabel.raise_()
        self.hepaLabel.raise_()
        self.hepaFilterStatus.raise_()
        self.differentialPressureShow.raise_()
        self.lcd1.raise_()
        self.horizontalLayoutWidget_7.raise_()
        self.displayArea.raise_()
        self.layoutWidget.raise_()
        self.downTemperatureButton.raise_()
        self.upTemperatureButton.raise_()
        self.medicalGasLabelTitle.raise_()
        self.logoDisplay.raise_()
        self.menuTitleName.raise_()
        self.leftMenuTitleLine.raise_()
        self.rightMenuTitleLine.raise_()
        self.hepa.raise_()
        self.speakerButton.raise_()
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.elapsedTimeLabel.setText(_translate("MainWindow", "Elapsed Time"))
        self.setTimeSetting.setText(_translate("MainWindow", "Set Time"))
        self.toolButton_9.setText(_translate("MainWindow", "..."))
        self.phoneCallingButton.setText(_translate("MainWindow", "..."))
        self.powerButton.setText(_translate("MainWindow", "STANDBY/CLEAN"))
        self.downTemperatureButton.setText(_translate("MainWindow", "Down"))
        self.upTemperatureButton.setText(_translate("MainWindow", "Up"))
        self.downHumidityButton.setText(_translate("MainWindow", "Down"))
        self.upHumidityButton.setText(_translate("MainWindow", "Up"))
        self.humidityLabelName.setText(_translate("MainWindow", "Humidity"))
        self.tempLabelName.setText(_translate("MainWindow", "Temperature"))
        self.otLighteningDetails.setText(_translate("MainWindow", "    Lightening"))
        self.ventiLationDetails.setText(_translate("MainWindow", "     Ventilation"))
        self.gasIndicator.setText(_translate("MainWindow", "                  Gas"))
        self.historyDetails.setText(_translate("MainWindow", "           History"))
        self.multiMediaDetails.setText(_translate("MainWindow", "   Multimedia"))
        self.nitrousOxide.setText(_translate("MainWindow", "N2O"))
        self.air.setText(_translate("MainWindow", "AIR"))
        self.air7.setText(_translate("MainWindow", "AIR7"))
        self.cabonDiOxide.setText(_translate("MainWindow", "CO2"))
        self.oxygen.setText(_translate("MainWindow", "O2"))
        self.vacuum.setText(_translate("MainWindow", "VAC"))
        self.ips.setText(_translate("MainWindow", "IPS"))
        self.settingsButton.setText(_translate("MainWindow", "Settings"))
        self.homeButton.setText(_translate("MainWindow", "..."))
        self.reset.setText(_translate("MainWindow", "Reset"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.addAdditonalChronosButton.setText(_translate("MainWindow", "Additional Chrono"))
        self.day_date_show.setText(_translate("MainWindow", "Date Show"))
        self.time_label.setText(_translate("MainWindow", "Time"))
        self.anaesthesiaTimeLabel.setText(_translate("MainWindow", "Anaesthesia  Time"))
        self.temeratureGraph.setText(_translate("MainWindow", "GRAPH"))
        self.humidityGraph.setText(_translate("MainWindow", "GRAPH"))
        self.tempShow.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">15.1</span></p></body></html>"))
        self.humidityShow.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">64.0</span></p></body></html>"))
        self.tempSetLabel.setText(_translate("MainWindow", "Set"))
        self.humiditySetLabel.setText(_translate("MainWindow", "Set"))
        self.tempSetShow.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">00</span></p><p><span style=\" font-weight:600;\"><br/></span></p></body></html>"))
        self.humiditySetShow.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">00</span></p><p><span style=\" font-weight:600;\"><br/></span></p></body></html>"))
        self.differentialLabel.setText(_translate("MainWindow", "Diffrential Pressure"))
        self.hepaLabel.setText(_translate("MainWindow", "Hepa Filter Status"))
        self.hepaFilterStatus.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">95%</span></p><p><span style=\" font-weight:600;\"><br/></span></p></body></html>"))
        self.differentialPressureShow.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">90</span></p></body></html>"))
        self.lcd1.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:72pt; font-weight:600;\">00:00</span></p></body></html>"))
        self.timerSet.setText(_translate("MainWindow", "Set"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.displayArea.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:72pt; font-weight:600; color:#ffa400;\">00:00:00</span></p></body></html>"))
        self.btnOn.setText(_translate("MainWindow", "On"))
        self.btnOff.setText(_translate("MainWindow", "Off"))
        self.medicalGasLabelTitle.setText(_translate("MainWindow", "Medical Gas"))
        self.logoDisplay.setText(_translate("MainWindow", "Logo Display"))
        self.time_show.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:72pt; font-weight:600;\">00:00</span></p></body></html>"))
        self.menuTitleName.setText(_translate("MainWindow", "TextLabel"))
        self.leftMenuTitleLine.setText(_translate("MainWindow", "TextLabel"))
        self.rightMenuTitleLine.setText(_translate("MainWindow", "TextLabel"))
        self.hepa.setText(_translate("MainWindow", "Hepa"))
        self.speakerButton.setText(_translate("MainWindow", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
