# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(2716, 954)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QMainWindow{background-color:black;}")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_24.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_24.setSpacing(6)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setSpacing(6)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setSpacing(6)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setSpacing(6)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_33 = QtWidgets.QGridLayout()
        self.gridLayout_33.setSpacing(6)
        self.gridLayout_33.setObjectName("gridLayout_33")
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_33.addItem(spacerItem, 0, 0, 1, 1)
        self.time_label = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_label.sizePolicy().hasHeightForWidth())
        self.time_label.setSizePolicy(sizePolicy)
        self.time_label.setMinimumSize(QtCore.QSize(41, 20))
        self.time_label.setMaximumSize(QtCore.QSize(41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.time_label.setFont(font)
        self.time_label.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.time_label.setObjectName("time_label")
        self.gridLayout_33.addWidget(self.time_label, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_33.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_33, 0, 1, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_17.addItem(spacerItem2, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(2, 147, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem3, 2, 0, 1, 1)
        self.gridLayout_34 = QtWidgets.QGridLayout()
        self.gridLayout_34.setSpacing(6)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.time_show = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_show.sizePolicy().hasHeightForWidth())
        self.time_show.setSizePolicy(sizePolicy)
        self.time_show.setMinimumSize(QtCore.QSize(600, 150))
        font = QtGui.QFont()
        font.setPointSize(72)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.time_show.setFont(font)
        self.time_show.setStyleSheet("QLabel { color: #FFFFFF; \n"
"                  font-size:72pt;\n"
"                  font-weight:600;}")
        self.time_show.setObjectName("time_show")
        self.gridLayout_34.addWidget(self.time_show, 0, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_34, 2, 1, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem4, 2, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_17.addItem(spacerItem5, 3, 2, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setSpacing(6)
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem6 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem6, 0, 0, 1, 1)
        self.setTimeSetting = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setTimeSetting.sizePolicy().hasHeightForWidth())
        self.setTimeSetting.setSizePolicy(sizePolicy)
        self.setTimeSetting.setMinimumSize(QtCore.QSize(41, 42))
        self.setTimeSetting.setMaximumSize(QtCore.QSize(42, 42))
        self.setTimeSetting.setStyleSheet("QToolButton#setTimeSetting{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#setTimeSetting:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/settings-clock-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setTimeSetting.setIcon(icon)
        self.setTimeSetting.setIconSize(QtCore.QSize(23, 23))
        self.setTimeSetting.setObjectName("setTimeSetting")
        self.gridLayout_14.addWidget(self.setTimeSetting, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem7, 0, 2, 1, 1)
        self.day_date_show = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.day_date_show.sizePolicy().hasHeightForWidth())
        self.day_date_show.setSizePolicy(sizePolicy)
        self.day_date_show.setMinimumSize(QtCore.QSize(351, 31))
        self.day_date_show.setStyleSheet("QLabel { color: #FFFFFF; \n"
"                  font-size:20pt;\n"
"                  font-weight:600;}")
        self.day_date_show.setObjectName("day_date_show")
        self.gridLayout_14.addWidget(self.day_date_show, 0, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem8, 0, 4, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_14, 4, 1, 1, 2)
        self.gridLayout_18.addLayout(self.gridLayout_17, 0, 0, 2, 1)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setSpacing(6)
        self.gridLayout_16.setObjectName("gridLayout_16")
        spacerItem9 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_16.addItem(spacerItem9, 1, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem10, 2, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem11 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem11, 0, 0, 1, 1)
        self.start = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start.sizePolicy().hasHeightForWidth())
        self.start.setSizePolicy(sizePolicy)
        self.start.setMinimumSize(QtCore.QSize(42, 42))
        self.start.setMaximumSize(QtCore.QSize(42, 42))
        self.start.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/play_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start.setIcon(icon1)
        self.start.setObjectName("start")
        self.gridLayout_9.addWidget(self.start, 0, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem12, 0, 2, 1, 1)
        self.reset = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset.sizePolicy().hasHeightForWidth())
        self.reset.setSizePolicy(sizePolicy)
        self.reset.setMinimumSize(QtCore.QSize(42, 42))
        self.reset.setMaximumSize(QtCore.QSize(42, 42))
        self.reset.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reset.setIcon(icon2)
        self.reset.setIconSize(QtCore.QSize(21, 21))
        self.reset.setObjectName("reset")
        self.gridLayout_9.addWidget(self.reset, 0, 3, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem13, 0, 4, 1, 1)
        self.addAdditonalChronosButton = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addAdditonalChronosButton.sizePolicy().hasHeightForWidth())
        self.addAdditonalChronosButton.setSizePolicy(sizePolicy)
        self.addAdditonalChronosButton.setMinimumSize(QtCore.QSize(141, 42))
        self.addAdditonalChronosButton.setMaximumSize(QtCore.QSize(147, 42))
        self.addAdditonalChronosButton.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.addAdditonalChronosButton.setIconSize(QtCore.QSize(21, 21))
        self.addAdditonalChronosButton.setObjectName("addAdditonalChronosButton")
        self.gridLayout_9.addWidget(self.addAdditonalChronosButton, 0, 5, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem14, 0, 6, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_9, 4, 1, 1, 2)
        self.gridLayout_28 = QtWidgets.QGridLayout()
        self.gridLayout_28.setSpacing(6)
        self.gridLayout_28.setObjectName("gridLayout_28")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_28.addItem(spacerItem15, 0, 0, 1, 1)
        self.elapsedTimeLabel = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elapsedTimeLabel.sizePolicy().hasHeightForWidth())
        self.elapsedTimeLabel.setSizePolicy(sizePolicy)
        self.elapsedTimeLabel.setMinimumSize(QtCore.QSize(100, 20))
        self.elapsedTimeLabel.setMaximumSize(QtCore.QSize(41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.elapsedTimeLabel.setFont(font)
        self.elapsedTimeLabel.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.elapsedTimeLabel.setObjectName("elapsedTimeLabel")
        self.gridLayout_28.addWidget(self.elapsedTimeLabel, 0, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_28.addItem(spacerItem16, 0, 2, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_28, 0, 1, 1, 2)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setSpacing(6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.lcd1 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd1.sizePolicy().hasHeightForWidth())
        self.lcd1.setSizePolicy(sizePolicy)
        self.lcd1.setMinimumSize(QtCore.QSize(600, 150))
        self.lcd1.setStyleSheet("QLabel { color: #FFFFFF; \n"
"                  font-size:72pt;\n"
"                  font-weight:600;}")
        self.lcd1.setObjectName("lcd1")
        self.gridLayout_15.addWidget(self.lcd1, 0, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_15, 2, 1, 1, 2)
        spacerItem17 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_16.addItem(spacerItem17, 3, 2, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem18, 2, 3, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_16, 0, 2, 2, 1)
        spacerItem19 = QtWidgets.QSpacerItem(17, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem19, 0, 3, 1, 1)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setSpacing(6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_29 = QtWidgets.QGridLayout()
        self.gridLayout_29.setSpacing(6)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.displayArea = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayArea.sizePolicy().hasHeightForWidth())
        self.displayArea.setSizePolicy(sizePolicy)
        self.displayArea.setMinimumSize(QtCore.QSize(600, 150))
        font = QtGui.QFont()
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.displayArea.setFont(font)
        self.displayArea.setStyleSheet("QLabel { color: #FFFF00; \n"
"                  font-size:72pt;\n"
"                  font-weight:600;}")
        self.displayArea.setObjectName("displayArea")
        self.gridLayout_29.addWidget(self.displayArea, 0, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_29, 2, 1, 1, 2)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem20 = QtWidgets.QSpacerItem(170, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem20, 0, 0, 1, 1)
        self.timerSet = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timerSet.sizePolicy().hasHeightForWidth())
        self.timerSet.setSizePolicy(sizePolicy)
        self.timerSet.setMinimumSize(QtCore.QSize(42, 42))
        self.timerSet.setMaximumSize(QtCore.QSize(42, 42))
        self.timerSet.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/time-settings-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.timerSet.setIcon(icon3)
        self.timerSet.setIconSize(QtCore.QSize(34, 34))
        self.timerSet.setObjectName("timerSet")
        self.gridLayout_10.addWidget(self.timerSet, 0, 1, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem21, 0, 2, 1, 1)
        self.startButton = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMinimumSize(QtCore.QSize(42, 42))
        self.startButton.setMaximumSize(QtCore.QSize(42, 42))
        self.startButton.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.startButton.setIcon(icon1)
        self.startButton.setObjectName("startButton")
        self.gridLayout_10.addWidget(self.startButton, 0, 3, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem22, 0, 4, 1, 1)
        self.resetButton = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetButton.sizePolicy().hasHeightForWidth())
        self.resetButton.setSizePolicy(sizePolicy)
        self.resetButton.setMinimumSize(QtCore.QSize(42, 42))
        self.resetButton.setMaximumSize(QtCore.QSize(42, 42))
        self.resetButton.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.resetButton.setIcon(icon2)
        self.resetButton.setIconSize(QtCore.QSize(21, 21))
        self.resetButton.setObjectName("resetButton")
        self.gridLayout_10.addWidget(self.resetButton, 0, 5, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(425, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem23, 0, 6, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_10, 4, 1, 1, 2)
        spacerItem24 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_13.addItem(spacerItem24, 1, 1, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem25, 2, 3, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem26, 2, 0, 1, 1)
        self.gridLayout_30 = QtWidgets.QGridLayout()
        self.gridLayout_30.setSpacing(6)
        self.gridLayout_30.setObjectName("gridLayout_30")
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_30.addItem(spacerItem27, 0, 0, 1, 1)
        self.anaesthesiaTimeLabel = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anaesthesiaTimeLabel.sizePolicy().hasHeightForWidth())
        self.anaesthesiaTimeLabel.setSizePolicy(sizePolicy)
        self.anaesthesiaTimeLabel.setMinimumSize(QtCore.QSize(141, 20))
        self.anaesthesiaTimeLabel.setMaximumSize(QtCore.QSize(41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.anaesthesiaTimeLabel.setFont(font)
        self.anaesthesiaTimeLabel.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.anaesthesiaTimeLabel.setObjectName("anaesthesiaTimeLabel")
        self.gridLayout_30.addWidget(self.anaesthesiaTimeLabel, 0, 1, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_30.addItem(spacerItem28, 0, 2, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_30, 0, 1, 1, 2)
        spacerItem29 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_13.addItem(spacerItem29, 3, 2, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_13, 0, 4, 2, 1)
        spacerItem30 = QtWidgets.QSpacerItem(17, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem30, 1, 1, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_18, 0, 0, 1, 3)
        self.gridLayout_38 = QtWidgets.QGridLayout()
        self.gridLayout_38.setSpacing(6)
        self.gridLayout_38.setObjectName("gridLayout_38")
        spacerItem31 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_38.addItem(spacerItem31, 0, 1, 1, 1)
        self.otLighteningDetails = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otLighteningDetails.sizePolicy().hasHeightForWidth())
        self.otLighteningDetails.setSizePolicy(sizePolicy)
        self.otLighteningDetails.setMinimumSize(QtCore.QSize(196, 42))
        self.otLighteningDetails.setMaximumSize(QtCore.QSize(199, 42))
        self.otLighteningDetails.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/lighting_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.otLighteningDetails.setIcon(icon4)
        self.otLighteningDetails.setCheckable(False)
        self.otLighteningDetails.setAutoRepeat(False)
        self.otLighteningDetails.setAutoExclusive(False)
        self.otLighteningDetails.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.otLighteningDetails.setObjectName("otLighteningDetails")
        self.gridLayout_38.addWidget(self.otLighteningDetails, 1, 0, 1, 2)
        spacerItem32 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_38.addItem(spacerItem32, 2, 1, 1, 1)
        self.ventiLationDetails = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ventiLationDetails.sizePolicy().hasHeightForWidth())
        self.ventiLationDetails.setSizePolicy(sizePolicy)
        self.ventiLationDetails.setMinimumSize(QtCore.QSize(196, 42))
        self.ventiLationDetails.setMaximumSize(QtCore.QSize(199, 42))
        self.ventiLationDetails.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/fan_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ventiLationDetails.setIcon(icon5)
        self.ventiLationDetails.setCheckable(False)
        self.ventiLationDetails.setAutoRepeat(False)
        self.ventiLationDetails.setAutoExclusive(False)
        self.ventiLationDetails.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.ventiLationDetails.setObjectName("ventiLationDetails")
        self.gridLayout_38.addWidget(self.ventiLationDetails, 3, 0, 1, 2)
        spacerItem33 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_38.addItem(spacerItem33, 4, 1, 1, 1)
        self.gasIndicator = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gasIndicator.sizePolicy().hasHeightForWidth())
        self.gasIndicator.setSizePolicy(sizePolicy)
        self.gasIndicator.setMinimumSize(QtCore.QSize(196, 42))
        self.gasIndicator.setMaximumSize(QtCore.QSize(199, 42))
        self.gasIndicator.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/pressure_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gasIndicator.setIcon(icon6)
        self.gasIndicator.setCheckable(False)
        self.gasIndicator.setAutoRepeat(False)
        self.gasIndicator.setAutoExclusive(False)
        self.gasIndicator.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.gasIndicator.setObjectName("gasIndicator")
        self.gridLayout_38.addWidget(self.gasIndicator, 5, 0, 1, 2)
        spacerItem34 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_38.addItem(spacerItem34, 6, 1, 1, 1)
        self.historyDetails = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.historyDetails.sizePolicy().hasHeightForWidth())
        self.historyDetails.setSizePolicy(sizePolicy)
        self.historyDetails.setMinimumSize(QtCore.QSize(196, 42))
        self.historyDetails.setMaximumSize(QtCore.QSize(199, 42))
        self.historyDetails.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icon/report_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.historyDetails.setIcon(icon7)
        self.historyDetails.setCheckable(False)
        self.historyDetails.setAutoRepeat(False)
        self.historyDetails.setAutoExclusive(False)
        self.historyDetails.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.historyDetails.setObjectName("historyDetails")
        self.gridLayout_38.addWidget(self.historyDetails, 7, 0, 1, 2)
        spacerItem35 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_38.addItem(spacerItem35, 8, 0, 1, 2)
        self.multiMediaDetails = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.multiMediaDetails.sizePolicy().hasHeightForWidth())
        self.multiMediaDetails.setSizePolicy(sizePolicy)
        self.multiMediaDetails.setMinimumSize(QtCore.QSize(196, 42))
        self.multiMediaDetails.setMaximumSize(QtCore.QSize(199, 42))
        self.multiMediaDetails.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icon/multimedia_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.multiMediaDetails.setIcon(icon8)
        self.multiMediaDetails.setCheckable(False)
        self.multiMediaDetails.setAutoRepeat(False)
        self.multiMediaDetails.setAutoExclusive(False)
        self.multiMediaDetails.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.multiMediaDetails.setObjectName("multiMediaDetails")
        self.gridLayout_38.addWidget(self.multiMediaDetails, 9, 0, 1, 2)
        spacerItem36 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_38.addItem(spacerItem36, 10, 0, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_38, 1, 0, 1, 1)
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setSpacing(6)
        self.gridLayout_22.setObjectName("gridLayout_22")
        spacerItem37 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_22.addItem(spacerItem37, 0, 2, 1, 1)
        self.centralwidget = QtWidgets.QWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1176, 500))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_22.addWidget(self.centralwidget, 1, 1, 2, 2)
        spacerItem38 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem38, 1, 3, 1, 1)
        spacerItem39 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem39, 2, 0, 1, 1)
        spacerItem40 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_22.addItem(spacerItem40, 3, 1, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_22, 1, 1, 2, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setSpacing(6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.humiditySetShow = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.humiditySetShow.sizePolicy().hasHeightForWidth())
        self.humiditySetShow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.humiditySetShow.setFont(font)
        self.humiditySetShow.setScaledContents(True)
        self.humiditySetShow.setObjectName("humiditySetShow")
        self.gridLayout_6.addWidget(self.humiditySetShow, 0, 3, 1, 1)
        spacerItem41 = QtWidgets.QSpacerItem(222, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem41, 0, 2, 1, 1)
        spacerItem42 = QtWidgets.QSpacerItem(62, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem42, 0, 4, 1, 1)
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem43, 0, 0, 1, 1)
        self.tempSetShow = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempSetShow.sizePolicy().hasHeightForWidth())
        self.tempSetShow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.tempSetShow.setFont(font)
        self.tempSetShow.setScaledContents(True)
        self.tempSetShow.setObjectName("tempSetShow")
        self.gridLayout_6.addWidget(self.tempSetShow, 0, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_6, 5, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem44 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem44, 0, 6, 1, 1)
        spacerItem45 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem45, 0, 0, 1, 1)
        self.tempIcon = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempIcon.sizePolicy().hasHeightForWidth())
        self.tempIcon.setSizePolicy(sizePolicy)
        self.tempIcon.setMinimumSize(QtCore.QSize(61, 60))
        self.tempIcon.setMaximumSize(QtCore.QSize(61, 60))
        self.tempIcon.setText("")
        self.tempIcon.setPixmap(QtGui.QPixmap("icon/thermometer_white.png"))
        self.tempIcon.setScaledContents(True)
        self.tempIcon.setObjectName("tempIcon")
        self.gridLayout_8.addWidget(self.tempIcon, 0, 1, 1, 1)
        spacerItem46 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem46, 0, 2, 1, 1)
        spacerItem47 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem47, 0, 8, 1, 1)
        self.humidityShow = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.humidityShow.sizePolicy().hasHeightForWidth())
        self.humidityShow.setSizePolicy(sizePolicy)
        self.humidityShow.setMinimumSize(QtCore.QSize(151, 70))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.humidityShow.setFont(font)
        self.humidityShow.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.humidityShow.setObjectName("humidityShow")
        self.gridLayout_8.addWidget(self.humidityShow, 0, 7, 1, 1)
        self.tempShow = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempShow.sizePolicy().hasHeightForWidth())
        self.tempShow.setSizePolicy(sizePolicy)
        self.tempShow.setMinimumSize(QtCore.QSize(121, 70))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.tempShow.setFont(font)
        self.tempShow.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.tempShow.setObjectName("tempShow")
        self.gridLayout_8.addWidget(self.tempShow, 0, 3, 1, 1)
        spacerItem48 = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem48, 0, 4, 1, 1)
        self.humidityIcon = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.humidityIcon.sizePolicy().hasHeightForWidth())
        self.humidityIcon.setSizePolicy(sizePolicy)
        self.humidityIcon.setMinimumSize(QtCore.QSize(51, 60))
        self.humidityIcon.setMaximumSize(QtCore.QSize(51, 60))
        self.humidityIcon.setText("")
        self.humidityIcon.setPixmap(QtGui.QPixmap("icon/humidity_60_60.png"))
        self.humidityIcon.setScaledContents(True)
        self.humidityIcon.setObjectName("humidityIcon")
        self.gridLayout_8.addWidget(self.humidityIcon, 0, 5, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_8, 2, 0, 1, 4)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem49 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem49, 0, 0, 1, 1)
        self.differentialLabel = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.differentialLabel.sizePolicy().hasHeightForWidth())
        self.differentialLabel.setSizePolicy(sizePolicy)
        self.differentialLabel.setMinimumSize(QtCore.QSize(141, 20))
        self.differentialLabel.setMaximumSize(QtCore.QSize(141, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.differentialLabel.setFont(font)
        self.differentialLabel.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.differentialLabel.setObjectName("differentialLabel")
        self.gridLayout_4.addWidget(self.differentialLabel, 0, 1, 1, 1)
        spacerItem50 = QtWidgets.QSpacerItem(132, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem50, 0, 2, 1, 1)
        self.hepaLabel = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hepaLabel.sizePolicy().hasHeightForWidth())
        self.hepaLabel.setSizePolicy(sizePolicy)
        self.hepaLabel.setMinimumSize(QtCore.QSize(131, 19))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hepaLabel.setFont(font)
        self.hepaLabel.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.hepaLabel.setObjectName("hepaLabel")
        self.gridLayout_4.addWidget(self.hepaLabel, 0, 3, 1, 1)
        spacerItem51 = QtWidgets.QSpacerItem(71, 18, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem51, 0, 4, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_4, 11, 0, 1, 4)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem52 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem52, 0, 0, 1, 1)
        self.differentialPressureShow = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.differentialPressureShow.sizePolicy().hasHeightForWidth())
        self.differentialPressureShow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.differentialPressureShow.setFont(font)
        self.differentialPressureShow.setScaledContents(True)
        self.differentialPressureShow.setObjectName("differentialPressureShow")
        self.gridLayout_5.addWidget(self.differentialPressureShow, 0, 1, 1, 1)
        spacerItem53 = QtWidgets.QSpacerItem(171, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem53, 0, 2, 1, 1)
        self.hepaFilterStatus = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hepaFilterStatus.sizePolicy().hasHeightForWidth())
        self.hepaFilterStatus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.hepaFilterStatus.setFont(font)
        self.hepaFilterStatus.setScaledContents(True)
        self.hepaFilterStatus.setObjectName("hepaFilterStatus")
        self.gridLayout_5.addWidget(self.hepaFilterStatus, 0, 3, 1, 1)
        spacerItem54 = QtWidgets.QSpacerItem(63, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem54, 0, 4, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_5, 13, 0, 1, 4)
        spacerItem55 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem55, 6, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem56 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem56, 0, 0, 1, 1)
        self.temeratureGraph = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temeratureGraph.sizePolicy().hasHeightForWidth())
        self.temeratureGraph.setSizePolicy(sizePolicy)
        self.temeratureGraph.setMinimumSize(QtCore.QSize(106, 41))
        self.temeratureGraph.setMaximumSize(QtCore.QSize(109, 41))
        self.temeratureGraph.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icon/temp_graph.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.temeratureGraph.setIcon(icon9)
        self.temeratureGraph.setIconSize(QtCore.QSize(24, 24))
        self.temeratureGraph.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.temeratureGraph.setObjectName("temeratureGraph")
        self.gridLayout_2.addWidget(self.temeratureGraph, 0, 1, 1, 1)
        spacerItem57 = QtWidgets.QSpacerItem(151, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem57, 0, 2, 1, 1)
        self.humidityGraph = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.humidityGraph.sizePolicy().hasHeightForWidth())
        self.humidityGraph.setSizePolicy(sizePolicy)
        self.humidityGraph.setMinimumSize(QtCore.QSize(106, 41))
        self.humidityGraph.setMaximumSize(QtCore.QSize(109, 41))
        self.humidityGraph.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icon/humidity_graph.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.humidityGraph.setIcon(icon10)
        self.humidityGraph.setIconSize(QtCore.QSize(24, 24))
        self.humidityGraph.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.humidityGraph.setObjectName("humidityGraph")
        self.gridLayout_2.addWidget(self.humidityGraph, 0, 3, 1, 1)
        spacerItem58 = QtWidgets.QSpacerItem(86, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem58, 0, 4, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_2, 9, 0, 1, 4)
        spacerItem59 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem59, 10, 0, 1, 1)
        spacerItem60 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem60, 8, 1, 1, 1)
        spacerItem61 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem61, 1, 3, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem62 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem62, 0, 0, 1, 1)
        self.downTemperatureButton = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downTemperatureButton.sizePolicy().hasHeightForWidth())
        self.downTemperatureButton.setSizePolicy(sizePolicy)
        self.downTemperatureButton.setMinimumSize(QtCore.QSize(42, 42))
        self.downTemperatureButton.setMaximumSize(QtCore.QSize(42, 42))
        self.downTemperatureButton.setStyleSheet("QToolButton#downTemperatureButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton#downTemperatureButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icon/down-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downTemperatureButton.setIcon(icon11)
        self.downTemperatureButton.setObjectName("downTemperatureButton")
        self.gridLayout_3.addWidget(self.downTemperatureButton, 0, 1, 1, 1)
        spacerItem63 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem63, 0, 2, 1, 1)
        self.upTemperatureButton = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upTemperatureButton.sizePolicy().hasHeightForWidth())
        self.upTemperatureButton.setSizePolicy(sizePolicy)
        self.upTemperatureButton.setMinimumSize(QtCore.QSize(42, 42))
        self.upTemperatureButton.setMaximumSize(QtCore.QSize(42, 42))
        self.upTemperatureButton.setStyleSheet("QToolButton#upTemperatureButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton#upTemperatureButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icon/up-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upTemperatureButton.setIcon(icon12)
        self.upTemperatureButton.setObjectName("upTemperatureButton")
        self.gridLayout_3.addWidget(self.upTemperatureButton, 0, 3, 1, 1)
        spacerItem64 = QtWidgets.QSpacerItem(163, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem64, 0, 4, 1, 1)
        self.downHumidityButton = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downHumidityButton.sizePolicy().hasHeightForWidth())
        self.downHumidityButton.setSizePolicy(sizePolicy)
        self.downHumidityButton.setMinimumSize(QtCore.QSize(42, 42))
        self.downHumidityButton.setMaximumSize(QtCore.QSize(42, 42))
        self.downHumidityButton.setStyleSheet("QToolButton#downHumidityButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton#downHumidityButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.downHumidityButton.setIcon(icon11)
        self.downHumidityButton.setObjectName("downHumidityButton")
        self.gridLayout_3.addWidget(self.downHumidityButton, 0, 5, 1, 1)
        spacerItem65 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem65, 0, 6, 1, 1)
        self.upHumidityButton = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upHumidityButton.sizePolicy().hasHeightForWidth())
        self.upHumidityButton.setSizePolicy(sizePolicy)
        self.upHumidityButton.setMinimumSize(QtCore.QSize(42, 42))
        self.upHumidityButton.setMaximumSize(QtCore.QSize(42, 42))
        self.upHumidityButton.setStyleSheet("QToolButton#upHumidityButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton#upHumidityButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.upHumidityButton.setIcon(icon12)
        self.upHumidityButton.setObjectName("upHumidityButton")
        self.gridLayout_3.addWidget(self.upHumidityButton, 0, 7, 1, 1)
        spacerItem66 = QtWidgets.QSpacerItem(89, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem66, 0, 8, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_3, 7, 0, 1, 4)
        spacerItem67 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem67, 12, 1, 1, 2)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setSpacing(6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem68 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem68, 0, 0, 1, 1)
        self.tempLabelName = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempLabelName.sizePolicy().hasHeightForWidth())
        self.tempLabelName.setSizePolicy(sizePolicy)
        self.tempLabelName.setMinimumSize(QtCore.QSize(91, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tempLabelName.setFont(font)
        self.tempLabelName.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.tempLabelName.setObjectName("tempLabelName")
        self.gridLayout_11.addWidget(self.tempLabelName, 0, 1, 1, 1)
        spacerItem69 = QtWidgets.QSpacerItem(167, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem69, 0, 2, 1, 1)
        self.humidityLabelName = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.humidityLabelName.sizePolicy().hasHeightForWidth())
        self.humidityLabelName.setSizePolicy(sizePolicy)
        self.humidityLabelName.setMinimumSize(QtCore.QSize(67, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.humidityLabelName.setFont(font)
        self.humidityLabelName.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.humidityLabelName.setObjectName("humidityLabelName")
        self.gridLayout_11.addWidget(self.humidityLabelName, 0, 3, 1, 1)
        spacerItem70 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem70, 0, 4, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 0, 0, 1, 4)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tempSetLabel = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempSetLabel.sizePolicy().hasHeightForWidth())
        self.tempSetLabel.setSizePolicy(sizePolicy)
        self.tempSetLabel.setMinimumSize(QtCore.QSize(31, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tempSetLabel.setFont(font)
        self.tempSetLabel.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.tempSetLabel.setObjectName("tempSetLabel")
        self.gridLayout_7.addWidget(self.tempSetLabel, 0, 1, 1, 1)
        spacerItem71 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem71, 0, 0, 1, 1)
        spacerItem72 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem72, 0, 2, 1, 1)
        spacerItem73 = QtWidgets.QSpacerItem(101, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem73, 0, 4, 1, 1)
        self.humiditySetLabel = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.humiditySetLabel.sizePolicy().hasHeightForWidth())
        self.humiditySetLabel.setSizePolicy(sizePolicy)
        self.humiditySetLabel.setMinimumSize(QtCore.QSize(31, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.humiditySetLabel.setFont(font)
        self.humiditySetLabel.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.humiditySetLabel.setObjectName("humiditySetLabel")
        self.gridLayout_7.addWidget(self.humiditySetLabel, 0, 3, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_7, 3, 0, 1, 4)
        spacerItem74 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem74, 4, 0, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_12, 1, 2, 1, 1)
        spacerItem75 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_23.addItem(spacerItem75, 2, 2, 1, 1)
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setSpacing(6)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setSpacing(6)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.logoDisplay = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoDisplay.sizePolicy().hasHeightForWidth())
        self.logoDisplay.setSizePolicy(sizePolicy)
        self.logoDisplay.setMinimumSize(QtCore.QSize(91, 61))
        self.logoDisplay.setMaximumSize(QtCore.QSize(91, 61))
        self.logoDisplay.setScaledContents(True)
        self.logoDisplay.setObjectName("logoDisplay")
        self.gridLayout_19.addWidget(self.logoDisplay, 0, 0, 1, 1)
        spacerItem76 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem76, 0, 1, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_19, 0, 0, 1, 1)
        spacerItem77 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem77, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.vacuum = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vacuum.sizePolicy().hasHeightForWidth())
        self.vacuum.setSizePolicy(sizePolicy)
        self.vacuum.setMinimumSize(QtCore.QSize(100, 42))
        self.vacuum.setStyleSheet("QToolButton#vacuum{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#vacuum:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.vacuum.setObjectName("vacuum")
        self.gridLayout.addWidget(self.vacuum, 1, 5, 1, 1)
        self.nitrousOxide = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nitrousOxide.sizePolicy().hasHeightForWidth())
        self.nitrousOxide.setSizePolicy(sizePolicy)
        self.nitrousOxide.setMinimumSize(QtCore.QSize(100, 42))
        self.nitrousOxide.setStyleSheet("QToolButton#nitrousOxide{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#nitrousOxide:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.nitrousOxide.setObjectName("nitrousOxide")
        self.gridLayout.addWidget(self.nitrousOxide, 1, 0, 1, 1)
        self.air = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.air.sizePolicy().hasHeightForWidth())
        self.air.setSizePolicy(sizePolicy)
        self.air.setMinimumSize(QtCore.QSize(100, 42))
        self.air.setStyleSheet("QToolButton#air{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#air:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.air.setObjectName("air")
        self.gridLayout.addWidget(self.air, 1, 1, 1, 1)
        self.air7 = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.air7.sizePolicy().hasHeightForWidth())
        self.air7.setSizePolicy(sizePolicy)
        self.air7.setMinimumSize(QtCore.QSize(100, 42))
        self.air7.setStyleSheet("QToolButton#air7{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#air7:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.air7.setObjectName("air7")
        self.gridLayout.addWidget(self.air7, 1, 2, 1, 1)
        self.medicalGasLabelTitle = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.medicalGasLabelTitle.sizePolicy().hasHeightForWidth())
        self.medicalGasLabelTitle.setSizePolicy(sizePolicy)
        self.medicalGasLabelTitle.setMinimumSize(QtCore.QSize(101, 21))
        self.medicalGasLabelTitle.setMaximumSize(QtCore.QSize(719, 21))
        self.medicalGasLabelTitle.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.medicalGasLabelTitle.setObjectName("medicalGasLabelTitle")
        self.gridLayout.addWidget(self.medicalGasLabelTitle, 0, 0, 1, 2)
        self.cabonDiOxide = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cabonDiOxide.sizePolicy().hasHeightForWidth())
        self.cabonDiOxide.setSizePolicy(sizePolicy)
        self.cabonDiOxide.setMinimumSize(QtCore.QSize(100, 42))
        self.cabonDiOxide.setStyleSheet("QToolButton#cabonDiOxide{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#cabonDiOxide:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.cabonDiOxide.setObjectName("cabonDiOxide")
        self.gridLayout.addWidget(self.cabonDiOxide, 1, 3, 1, 1)
        self.ips = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ips.sizePolicy().hasHeightForWidth())
        self.ips.setSizePolicy(sizePolicy)
        self.ips.setMinimumSize(QtCore.QSize(100, 42))
        self.ips.setStyleSheet("QToolButton#ips{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#ips:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.ips.setObjectName("ips")
        self.gridLayout.addWidget(self.ips, 1, 6, 1, 1)
        self.oxygen = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oxygen.sizePolicy().hasHeightForWidth())
        self.oxygen.setSizePolicy(sizePolicy)
        self.oxygen.setMinimumSize(QtCore.QSize(100, 42))
        self.oxygen.setStyleSheet("QToolButton#oxygen{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#oxygen:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.oxygen.setObjectName("oxygen")
        self.gridLayout.addWidget(self.oxygen, 1, 4, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout, 0, 2, 1, 1)
        spacerItem78 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem78, 0, 3, 1, 1)
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setSpacing(6)
        self.gridLayout_20.setObjectName("gridLayout_20")
        spacerItem79 = QtWidgets.QSpacerItem(20, 21, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_20.addItem(spacerItem79, 0, 0, 1, 1)
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setSpacing(6)
        self.gridLayout_27.setObjectName("gridLayout_27")
        spacerItem80 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem80, 0, 0, 1, 1)
        self.toolButton_9 = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_9.sizePolicy().hasHeightForWidth())
        self.toolButton_9.setSizePolicy(sizePolicy)
        self.toolButton_9.setMinimumSize(QtCore.QSize(42, 42))
        self.toolButton_9.setMaximumSize(QtCore.QSize(42, 42))
        self.toolButton_9.setStyleSheet("QToolButton#toolButton_9{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#toolButton_9:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.toolButton_9.setObjectName("toolButton_9")
        self.gridLayout_27.addWidget(self.toolButton_9, 0, 1, 1, 1)
        spacerItem81 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem81, 0, 2, 1, 1)
        self.phoneCallingButton = QtWidgets.QToolButton(self.centralWidget)
        self.phoneCallingButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phoneCallingButton.sizePolicy().hasHeightForWidth())
        self.phoneCallingButton.setSizePolicy(sizePolicy)
        self.phoneCallingButton.setMinimumSize(QtCore.QSize(42, 42))
        self.phoneCallingButton.setMaximumSize(QtCore.QSize(42, 42))
        self.phoneCallingButton.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icon/phone-call-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.phoneCallingButton.setIcon(icon13)
        self.phoneCallingButton.setIconSize(QtCore.QSize(44, 44))
        self.phoneCallingButton.setObjectName("phoneCallingButton")
        self.gridLayout_27.addWidget(self.phoneCallingButton, 0, 3, 1, 1)
        spacerItem82 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem82, 0, 4, 1, 1)
        self.powerButton = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.powerButton.sizePolicy().hasHeightForWidth())
        self.powerButton.setSizePolicy(sizePolicy)
        self.powerButton.setMinimumSize(QtCore.QSize(121, 42))
        self.powerButton.setMaximumSize(QtCore.QSize(121, 42))
        self.powerButton.setStyleSheet("QToolButton#powerButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#powerButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icon/power_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.powerButton.setIcon(icon14)
        self.powerButton.setObjectName("powerButton")
        self.gridLayout_27.addWidget(self.powerButton, 0, 5, 1, 1)
        spacerItem83 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem83, 0, 6, 1, 1)
        self.settingsButton = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsButton.sizePolicy().hasHeightForWidth())
        self.settingsButton.setSizePolicy(sizePolicy)
        self.settingsButton.setMinimumSize(QtCore.QSize(42, 42))
        self.settingsButton.setMaximumSize(QtCore.QSize(42, 42))
        self.settingsButton.setStyleSheet("QToolButton#settingsButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#settingsButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("icon/settings_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsButton.setIcon(icon15)
        self.settingsButton.setIconSize(QtCore.QSize(24, 24))
        self.settingsButton.setObjectName("settingsButton")
        self.gridLayout_27.addWidget(self.settingsButton, 0, 7, 1, 1)
        spacerItem84 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem84, 0, 8, 1, 1)
        self.homeButton = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homeButton.sizePolicy().hasHeightForWidth())
        self.homeButton.setSizePolicy(sizePolicy)
        self.homeButton.setMinimumSize(QtCore.QSize(42, 42))
        self.homeButton.setMaximumSize(QtCore.QSize(42, 42))
        self.homeButton.setStyleSheet("QToolButton#homeButton{\n"
"    border-style: outset;\n"
"    border-width:1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton#homeButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("icon/home_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeButton.setIcon(icon16)
        self.homeButton.setIconSize(QtCore.QSize(24, 24))
        self.homeButton.setObjectName("homeButton")
        self.gridLayout_27.addWidget(self.homeButton, 0, 9, 1, 1)
        spacerItem85 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem85, 0, 10, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_27, 1, 0, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_20, 0, 4, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_21, 3, 0, 1, 3)
        self.gridLayout_24.addLayout(self.gridLayout_23, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.time_label.setText(_translate("MainWindow", "Time"))
        self.time_show.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:72pt; font-weight:600;\">00:00</span></p></body></html>"))
        self.setTimeSetting.setText(_translate("MainWindow", "Set Time"))
        self.day_date_show.setText(_translate("MainWindow", "Date Show"))
        self.start.setText(_translate("MainWindow", "Play and Pause"))
        self.reset.setText(_translate("MainWindow", "Reset"))
        self.addAdditonalChronosButton.setText(_translate("MainWindow", "Additional Chronos"))
        self.elapsedTimeLabel.setText(_translate("MainWindow", "Elapsed Time"))
        self.lcd1.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:72pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">00:00</p></body></html>"))
        self.displayArea.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:72pt; font-weight:600; color:#ffa400;\">00:00:00</span></p></body></html>"))
        self.timerSet.setText(_translate("MainWindow", "Set"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.anaesthesiaTimeLabel.setText(_translate("MainWindow", "Anaesthesia  Time"))
        self.otLighteningDetails.setText(_translate("MainWindow", "          Lightening"))
        self.ventiLationDetails.setText(_translate("MainWindow", "           Ventilation"))
        self.gasIndicator.setText(_translate("MainWindow", "           Gas"))
        self.historyDetails.setText(_translate("MainWindow", "           History"))
        self.multiMediaDetails.setText(_translate("MainWindow", "           Multimedia"))
        self.humiditySetShow.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">00</p></body></html>"))
        self.tempSetShow.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">00</p></body></html>"))
        self.humidityShow.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">64.0</span></p></body></html>"))
        self.tempShow.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt;\">15.3</span></p></body></html>"))
        self.differentialLabel.setText(_translate("MainWindow", "Diffrential Pressure"))
        self.hepaLabel.setText(_translate("MainWindow", "Hepa Filter Status"))
        self.differentialPressureShow.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">90</p></body></html>"))
        self.hepaFilterStatus.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">95%</p></body></html>"))
        self.temeratureGraph.setText(_translate("MainWindow", "GRAPH"))
        self.humidityGraph.setText(_translate("MainWindow", "GRAPH"))
        self.downTemperatureButton.setText(_translate("MainWindow", "Down"))
        self.upTemperatureButton.setText(_translate("MainWindow", "Up"))
        self.downHumidityButton.setText(_translate("MainWindow", "Down"))
        self.upHumidityButton.setText(_translate("MainWindow", "Up"))
        self.tempLabelName.setText(_translate("MainWindow", "Temperature"))
        self.humidityLabelName.setText(_translate("MainWindow", " Humidity"))
        self.tempSetLabel.setText(_translate("MainWindow", "Set"))
        self.humiditySetLabel.setText(_translate("MainWindow", "Set"))
        self.logoDisplay.setText(_translate("MainWindow", "Logo Display"))
        self.vacuum.setText(_translate("MainWindow", "VAC"))
        self.nitrousOxide.setText(_translate("MainWindow", "N2O"))
        self.air.setText(_translate("MainWindow", "AIR"))
        self.air7.setText(_translate("MainWindow", "AIR7"))
        self.medicalGasLabelTitle.setText(_translate("MainWindow", "Medical Gas"))
        self.cabonDiOxide.setText(_translate("MainWindow", "CO2"))
        self.ips.setText(_translate("MainWindow", "IPS"))
        self.oxygen.setText(_translate("MainWindow", "O2"))
        self.toolButton_9.setText(_translate("MainWindow", "..."))
        self.phoneCallingButton.setText(_translate("MainWindow", "..."))
        self.powerButton.setText(_translate("MainWindow", "STANDBY/CLEAN"))
        self.settingsButton.setText(_translate("MainWindow", "Settings"))
        self.homeButton.setText(_translate("MainWindow", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
