# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'otLightening.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(916, 526)
        Form.setMinimumSize(QtCore.QSize(674, 388))
        self.gridLayout_15 = QtWidgets.QGridLayout(Form)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        spacerItem = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem, 0, 2, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lightLabel1 = QtWidgets.QLabel(Form)
        self.lightLabel1.setMinimumSize(QtCore.QSize(91, 19))
        self.lightLabel1.setMaximumSize(QtCore.QSize(91, 19))
        self.lightLabel1.setObjectName("lightLabel1")
        self.gridLayout_5.addWidget(self.lightLabel1, 0, 2, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 1, 0, 1, 1)
        self.lightBulb1 = QtWidgets.QLabel(Form)
        self.lightBulb1.setMinimumSize(QtCore.QSize(41, 41))
        self.lightBulb1.setMaximumSize(QtCore.QSize(41, 41))
        self.lightBulb1.setStyleSheet("QLabel { \n"
"color: #000000; \n"
"}")
        self.lightBulb1.setText("")
        self.lightBulb1.setPixmap(QtGui.QPixmap("icon/light-bulb.png"))
        self.lightBulb1.setScaledContents(True)
        self.lightBulb1.setObjectName("lightBulb1")
        self.gridLayout_5.addWidget(self.lightBulb1, 1, 1, 1, 1)
        self.toggleContainerGasL1 = QtWidgets.QWidget(Form)
        self.toggleContainerGasL1.setMinimumSize(QtCore.QSize(111, 51))
        self.toggleContainerGasL1.setMaximumSize(QtCore.QSize(111, 51))
        self.toggleContainerGasL1.setObjectName("toggleContainerGasL1")
        self.gridLayout_5.addWidget(self.toggleContainerGasL1, 1, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 1, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 2, 0, 1, 1)
        self.light1Decrement = QtWidgets.QToolButton(Form)
        self.light1Decrement.setMinimumSize(QtCore.QSize(42, 42))
        self.light1Decrement.setMaximumSize(QtCore.QSize(42, 42))
        self.light1Decrement.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px; \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/minus_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.light1Decrement.setIcon(icon)
        self.light1Decrement.setObjectName("light1Decrement")
        self.gridLayout_5.addWidget(self.light1Decrement, 2, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 2, 2, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.light1_2 = QtWidgets.QLabel(Form)
        self.light1_2.setMinimumSize(QtCore.QSize(8, 13))
        self.light1_2.setMaximumSize(QtCore.QSize(8, 13))
        self.light1_2.setStyleSheet("QLabel{\n"
"   border-style: outset;\n"
"    padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
"   \n"
" \n"
"  background-color:black;\n"
"}")
        self.light1_2.setText("")
        self.light1_2.setObjectName("light1_2")
        self.gridLayout_2.addWidget(self.light1_2, 0, 1, 1, 1,QtCore.Qt.AlignBottom)
        self.light1_4 = QtWidgets.QLabel(Form)
        self.light1_4.setMinimumSize(QtCore.QSize(8, 23))
        self.light1_4.setMaximumSize(QtCore.QSize(8, 23))
        self.light1_4.setStyleSheet("QLabel{\n"
"   border-style: outset;\n"
"  padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
" \n"
" \n"
"  background-color:black;\n"
"}")
        self.light1_4.setText("")
        self.light1_4.setObjectName("light1_4")
        self.gridLayout_2.addWidget(self.light1_4, 0, 3, 1, 1,QtCore.Qt.AlignBottom)
        self.light1_7 = QtWidgets.QLabel(Form)
        self.light1_7.setMinimumSize(QtCore.QSize(8, 38))
        self.light1_7.setMaximumSize(QtCore.QSize(8, 38))
        self.light1_7.setStyleSheet("QLabel{\n"
"   border-style: outset;\n"
"  padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
" \n"
"   \n"
"  background-color:black;\n"
"}")
        self.light1_7.setText("")
        self.light1_7.setObjectName("light1_7")
        self.gridLayout_2.addWidget(self.light1_7, 0, 6, 1, 1,QtCore.Qt.AlignBottom)
        self.light1_5 = QtWidgets.QLabel(Form)
        self.light1_5.setMinimumSize(QtCore.QSize(8, 28))
        self.light1_5.setMaximumSize(QtCore.QSize(8, 28))
        self.light1_5.setStyleSheet("QLabel{\n"
"   border-style: outset;\n"
"    padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px; \n"
"  background-color:black;\n"
"}")
        self.light1_5.setText("")
        self.light1_5.setObjectName("light1_5")
        self.gridLayout_2.addWidget(self.light1_5, 0, 4, 1, 1,QtCore.Qt.AlignBottom)
        self.light1_8 = QtWidgets.QLabel(Form)
        self.light1_8.setMinimumSize(QtCore.QSize(8, 43))
        self.light1_8.setMaximumSize(QtCore.QSize(8, 43))
        self.light1_8.setStyleSheet("QLabel{\n"
"  border-style: outset;\n"
"   padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
" \n"
" \n"
"  background-color:black;\n"
"}")
        self.light1_8.setText("")
        self.light1_8.setObjectName("light1_8")
        self.gridLayout_2.addWidget(self.light1_8, 0, 7, 1, 1,QtCore.Qt.AlignBottom)
        self.light1_1 = QtWidgets.QLabel(Form)
        self.light1_1.setEnabled(True)
        self.light1_1.setMinimumSize(QtCore.QSize(8, 8))
        self.light1_1.setMaximumSize(QtCore.QSize(8, 8))
        self.light1_1.setStyleSheet("QLabel{\n"
" border-style: outset;\n"
"    padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
"   \n"
"  background-color:black;\n"
"}")
        self.light1_1.setText("")
        self.light1_1.setObjectName("light1_1")
        self.gridLayout_2.addWidget(self.light1_1, 0, 0, 1, 1,QtCore.Qt.AlignBottom)
        self.light1_6 = QtWidgets.QLabel(Form)
        self.light1_6.setMinimumSize(QtCore.QSize(8, 33))
        self.light1_6.setMaximumSize(QtCore.QSize(8, 33))
        self.light1_6.setStyleSheet("QLabel{\n"
"   border-style: outset;\n"
"   padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
" \n"
" \n"
"  background-color:black;\n"
"}")
        self.light1_6.setText("")
        self.light1_6.setObjectName("light1_6")
        self.gridLayout_2.addWidget(self.light1_6, 0, 5, 1, 1,QtCore.Qt.AlignBottom)
        self.light1_9 = QtWidgets.QLabel(Form)
        self.light1_9.setMinimumSize(QtCore.QSize(8, 48))
        self.light1_9.setMaximumSize(QtCore.QSize(8, 48))
        self.light1_9.setStyleSheet("QLabel{\n"
"  border-style: outset;\n"
"  padding:2px;  \n"
"    border-radius:4px;\n"
"    \n"
"   border-width: 2px;\n"
" \n"
" \n"
"  background-color:black;\n"
"}")
        self.light1_9.setText("")
        self.light1_9.setObjectName("light1_9")
        self.gridLayout_2.addWidget(self.light1_9, 0, 8, 1, 1,QtCore.Qt.AlignBottom)
        self.light1_3 = QtWidgets.QLabel(Form)
        self.light1_3.setMinimumSize(QtCore.QSize(8, 18))
        self.light1_3.setMaximumSize(QtCore.QSize(8, 18))
        self.light1_3.setStyleSheet("QLabel{\n"
"   border-style: outset;\n"
"  padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
" \n"
" \n"
"  background-color:black;\n"
"}")
        self.light1_3.setText("")
        self.light1_3.setObjectName("light1_3")
        self.gridLayout_2.addWidget(self.light1_3, 0, 2, 1, 1,QtCore.Qt.AlignBottom)
        self.light1_10 = QtWidgets.QLabel(Form)
        self.light1_10.setMinimumSize(QtCore.QSize(8, 53))
        self.light1_10.setMaximumSize(QtCore.QSize(8, 53))
        self.light1_10.setStyleSheet("QLabel{\n"
"  border-style: outset;\n"
"  padding:2px;  \n"
"    border-radius:4px;\n"
"    \n"
"   border-width: 2px;\n"
" \n"
" \n"
"  background-color:black;\n"
"}")
        self.light1_10.setText("")
        self.light1_10.setObjectName("light1_10")
        self.gridLayout_2.addWidget(self.light1_10, 0, 9, 1, 1,QtCore.Qt.AlignBottom)
        self.gridLayout_5.addLayout(self.gridLayout_2, 2, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 2, 4, 1, 1)
        self.light1Increment = QtWidgets.QToolButton(Form)
        self.light1Increment.setMinimumSize(QtCore.QSize(42, 42))
        self.light1Increment.setMaximumSize(QtCore.QSize(42, 42))
        self.light1Increment.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px; \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/plus-sign-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.light1Increment.setIcon(icon1)
        self.light1Increment.setObjectName("light1Increment")
        self.gridLayout_5.addWidget(self.light1Increment, 2, 5, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem6, 2, 6, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_5, 1, 0, 2, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lightLabel2 = QtWidgets.QLabel(Form)
        self.lightLabel2.setMinimumSize(QtCore.QSize(91, 19))
        self.lightLabel2.setMaximumSize(QtCore.QSize(91, 19))
        self.lightLabel2.setObjectName("lightLabel2")
        self.gridLayout_6.addWidget(self.lightLabel2, 0, 2, 1, 2)
        spacerItem7 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem7, 1, 0, 1, 1)
        self.lightBulb2 = QtWidgets.QLabel(Form)
        self.lightBulb2.setMinimumSize(QtCore.QSize(41, 41))
        self.lightBulb2.setMaximumSize(QtCore.QSize(41, 41))
        self.lightBulb2.setStyleSheet("QLabel { \n"
"color: #000000; \n"
"}")
        self.lightBulb2.setText("")
        self.lightBulb2.setPixmap(QtGui.QPixmap("icon/light-bulb.png"))
        self.lightBulb2.setScaledContents(True)
        self.lightBulb2.setObjectName("lightBulb2")
        self.gridLayout_6.addWidget(self.lightBulb2, 1, 1, 1, 1)
        self.toggleContainerGasL2 = QtWidgets.QWidget(Form)
        self.toggleContainerGasL2.setMinimumSize(QtCore.QSize(111, 51))
        self.toggleContainerGasL2.setMaximumSize(QtCore.QSize(111, 51))
        self.toggleContainerGasL2.setObjectName("toggleContainerGasL2")
        self.gridLayout_6.addWidget(self.toggleContainerGasL2, 1, 2, 1, 2)
        spacerItem8 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem8, 1, 5, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem9, 2, 0, 1, 1)
        self.light2Decrement = QtWidgets.QToolButton(Form)
        self.light2Decrement.setMinimumSize(QtCore.QSize(42, 42))
        self.light2Decrement.setMaximumSize(QtCore.QSize(42, 42))
        self.light2Decrement.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px; \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.light2Decrement.setIcon(icon)
        self.light2Decrement.setObjectName("light2Decrement")
        self.gridLayout_6.addWidget(self.light2Decrement, 2, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem10, 2, 2, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.light2_1 = QtWidgets.QLabel(Form)
        self.light2_1.setEnabled(True)
        self.light2_1.setMinimumSize(QtCore.QSize(8, 8))
        self.light2_1.setMaximumSize(QtCore.QSize(8, 8))
        self.light2_1.setStyleSheet("QLabel{\n"
" border-style: outset;\n"
"    padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
"   \n"
"  background-color:black;\n"
"}")
        self.light2_1.setText("")
        self.light2_1.setObjectName("light2_1")
        self.gridLayout_3.addWidget(self.light2_1, 0, 0, 1, 1,QtCore.Qt.AlignBottom)
        self.light2_2 = QtWidgets.QLabel(Form)
        self.light2_2.setMinimumSize(QtCore.QSize(8, 13))
        self.light2_2.setMaximumSize(QtCore.QSize(8, 13))
        self.light2_2.setStyleSheet("QLabel{\n"
"   border-style: outset;\n"
"    padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
"   \n"
" \n"
"  background-color:black;\n"
"}")
        self.light2_2.setText("")
        self.light2_2.setObjectName("light2_2")
        self.gridLayout_3.addWidget(self.light2_2, 0, 1, 1, 1,QtCore.Qt.AlignBottom)
        self.light2_3 = QtWidgets.QLabel(Form)
        self.light2_3.setMinimumSize(QtCore.QSize(8, 18))
        self.light2_3.setMaximumSize(QtCore.QSize(8, 18))
        self.light2_3.setStyleSheet("QLabel{\n"
"   border-style: outset;\n"
"  padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
" \n"
" \n"
"  background-color:black;\n"
"}")
        self.light2_3.setText("")
        self.light2_3.setObjectName("light2_3")
        self.gridLayout_3.addWidget(self.light2_3, 0, 2, 1, 1,QtCore.Qt.AlignBottom)
        self.light2_4 = QtWidgets.QLabel(Form)
        self.light2_4.setMinimumSize(QtCore.QSize(8, 23))
        self.light2_4.setMaximumSize(QtCore.QSize(8, 23))
        self.light2_4.setStyleSheet("QLabel{\n"
"   border-style: outset;\n"
"  padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
" \n"
" \n"
"  background-color:black;\n"
"}")
        self.light2_4.setText("")
        self.light2_4.setObjectName("light2_4")
        self.gridLayout_3.addWidget(self.light2_4, 0, 3, 1, 1,QtCore.Qt.AlignBottom)
        self.light2_5 = QtWidgets.QLabel(Form)
        self.light2_5.setMinimumSize(QtCore.QSize(8, 28))
        self.light2_5.setMaximumSize(QtCore.QSize(8, 28))
        self.light2_5.setStyleSheet("QLabel{\n"
"   border-style: outset;\n"
"    padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px; \n"
"  background-color:black;\n"
"}")
        self.light2_5.setText("")
        self.light2_5.setObjectName("light2_5")
        self.gridLayout_3.addWidget(self.light2_5, 0, 4, 1, 1,QtCore.Qt.AlignBottom)
        self.light2_6 = QtWidgets.QLabel(Form)
        self.light2_6.setMinimumSize(QtCore.QSize(8, 33))
        self.light2_6.setMaximumSize(QtCore.QSize(8, 33))
        self.light2_6.setStyleSheet("QLabel{\n"
"   border-style: outset;\n"
"   padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
" \n"
" \n"
"  background-color:black;\n"
"}")
        self.light2_6.setText("")
        self.light2_6.setObjectName("light2_6")
        self.gridLayout_3.addWidget(self.light2_6, 0, 5, 1, 1,QtCore.Qt.AlignBottom)
        self.light2_7 = QtWidgets.QLabel(Form)
        self.light2_7.setMinimumSize(QtCore.QSize(8, 38))
        self.light2_7.setMaximumSize(QtCore.QSize(8, 38))
        self.light2_7.setStyleSheet("QLabel{\n"
"   border-style: outset;\n"
"  padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
" \n"
"   \n"
"  background-color:black;\n"
"}")
        self.light2_7.setText("")
        self.light2_7.setObjectName("light2_7")
        self.gridLayout_3.addWidget(self.light2_7, 0, 6, 1, 1,QtCore.Qt.AlignBottom)
        self.light2_8 = QtWidgets.QLabel(Form)
        self.light2_8.setMinimumSize(QtCore.QSize(8, 43))
        self.light2_8.setMaximumSize(QtCore.QSize(8, 43))
        self.light2_8.setStyleSheet("QLabel{\n"
"  border-style: outset;\n"
"   padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
" \n"
" \n"
"  background-color:black;\n"
"}")
        self.light2_8.setText("")
        self.light2_8.setObjectName("light2_8")
        self.gridLayout_3.addWidget(self.light2_8, 0, 7, 1, 1,QtCore.Qt.AlignBottom)
        self.light2_9 = QtWidgets.QLabel(Form)
        self.light2_9.setMinimumSize(QtCore.QSize(8, 48))
        self.light2_9.setMaximumSize(QtCore.QSize(8, 48))
        self.light2_9.setStyleSheet("QLabel{\n"
"  border-style: outset;\n"
"  padding:2px;  \n"
"    border-radius:4px;\n"
"    \n"
"   border-width: 2px;\n"
" \n"
" \n"
"  background-color:black;\n"
"}")
        self.light2_9.setText("")
        self.light2_9.setObjectName("light2_9")
        self.gridLayout_3.addWidget(self.light2_9, 0, 8, 1, 1,QtCore.Qt.AlignBottom)
        self.light2_10 = QtWidgets.QLabel(Form)
        self.light2_10.setMinimumSize(QtCore.QSize(8, 53))
        self.light2_10.setMaximumSize(QtCore.QSize(8, 53))
        self.light2_10.setStyleSheet("QLabel{\n"
"  border-style: outset;\n"
"  padding:2px;  \n"
"    border-radius:4px;\n"
"    \n"
"   border-width: 2px;\n"
" \n"
" \n"
"  background-color:black;\n"
"}")
        self.light2_10.setText("")
        self.light2_10.setObjectName("light2_10")
        self.gridLayout_3.addWidget(self.light2_10, 0, 9, 1, 1,QtCore.Qt.AlignBottom)
        self.gridLayout_6.addLayout(self.gridLayout_3, 2, 3, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem11, 2, 4, 1, 1)
        self.light2Increment = QtWidgets.QToolButton(Form)
        self.light2Increment.setMinimumSize(QtCore.QSize(42, 42))
        self.light2Increment.setMaximumSize(QtCore.QSize(42, 42))
        self.light2Increment.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px; \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.light2Increment.setIcon(icon1)
        self.light2Increment.setObjectName("light2Increment")
        self.gridLayout_6.addWidget(self.light2Increment, 2, 5, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem12, 2, 6, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_6, 1, 1, 2, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lightLabel3 = QtWidgets.QLabel(Form)
        self.lightLabel3.setMinimumSize(QtCore.QSize(41, 19))
        self.lightLabel3.setMaximumSize(QtCore.QSize(41, 19))
        self.lightLabel3.setObjectName("lightLabel3")
        self.gridLayout_8.addWidget(self.lightLabel3, 0, 1, 1, 1, QtCore.Qt.AlignTop)
        self.otLightBulb1 = QtWidgets.QLabel(Form)
        self.otLightBulb1.setMinimumSize(QtCore.QSize(31, 31))
        self.otLightBulb1.setMaximumSize(QtCore.QSize(31, 31))
        self.otLightBulb1.setStyleSheet("QLabel { \n"
"color: #000000; \n"
"}")
        self.otLightBulb1.setText("")
        self.otLightBulb1.setPixmap(QtGui.QPixmap("icon/lights.png"))
        self.otLightBulb1.setScaledContents(True)
        self.otLightBulb1.setObjectName("otLightBulb1")
        self.gridLayout_8.addWidget(self.otLightBulb1, 1, 0, 1, 1)
        self.toggleContainerOT1 = QtWidgets.QWidget(Form)
        self.toggleContainerOT1.setMinimumSize(QtCore.QSize(111, 51))
        self.toggleContainerOT1.setMaximumSize(QtCore.QSize(111, 51))
        self.toggleContainerOT1.setObjectName("toggleContainerOT1")
        self.gridLayout_8.addWidget(self.toggleContainerOT1, 1, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_8, 1, 2, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem13, 2, 2, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setMinimumSize(QtCore.QSize(581, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_14.addWidget(self.line, 1, 0, 1, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem14 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem14, 0, 2, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lightLabel4 = QtWidgets.QLabel(Form)
        self.lightLabel4.setMinimumSize(QtCore.QSize(81, 19))
        self.lightLabel4.setMaximumSize(QtCore.QSize(81, 19))
        self.lightLabel4.setObjectName("lightLabel4")
        self.gridLayout_11.addWidget(self.lightLabel4, 0, 2, 1, 2)
        spacerItem15 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem15, 1, 0, 1, 1)
        self.lightBulb3 = QtWidgets.QLabel(Form)
        self.lightBulb3.setMinimumSize(QtCore.QSize(41, 41))
        self.lightBulb3.setMaximumSize(QtCore.QSize(41, 41))
        self.lightBulb3.setStyleSheet("QLabel { \n"
"color: #000000; \n"
"}")
        self.lightBulb3.setText("")
        self.lightBulb3.setPixmap(QtGui.QPixmap("icon/light-bulb.png"))
        self.lightBulb3.setScaledContents(True)
        self.lightBulb3.setObjectName("lightBulb3")
        self.gridLayout_11.addWidget(self.lightBulb3, 1, 1, 1, 1)
        self.toggleContainer = QtWidgets.QWidget(Form)
        self.toggleContainer.setMinimumSize(QtCore.QSize(111, 51))
        self.toggleContainer.setMaximumSize(QtCore.QSize(111, 51))
        self.toggleContainer.setObjectName("toggleContainer")
        self.gridLayout_11.addWidget(self.toggleContainer, 1, 3, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem16, 1, 5, 1, 2)
        spacerItem17 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem17, 2, 0, 1, 1)
        self.light3Decrement = QtWidgets.QToolButton(Form)
        self.light3Decrement.setMinimumSize(QtCore.QSize(42, 42))
        self.light3Decrement.setMaximumSize(QtCore.QSize(42, 42))
        self.light3Decrement.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px; \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.light3Decrement.setIcon(icon)
        self.light3Decrement.setObjectName("light3Decrement")
        self.gridLayout_11.addWidget(self.light3Decrement, 2, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem18, 2, 2, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.light3_1 = QtWidgets.QLabel(Form)
        self.light3_1.setEnabled(True)
        self.light3_1.setMinimumSize(QtCore.QSize(8, 8))
        self.light3_1.setMaximumSize(QtCore.QSize(8, 8))
        self.light3_1.setStyleSheet("QLabel{\n"
" border-style: outset;\n"
"    padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
"   \n"
"  background-color:black;\n"
"}")
        self.light3_1.setText("")
        self.light3_1.setObjectName("light3_1")
        self.gridLayout.addWidget(self.light3_1, 0, 0, 1, 1,QtCore.Qt.AlignBottom)
        self.light3_2 = QtWidgets.QLabel(Form)
        self.light3_2.setMinimumSize(QtCore.QSize(8, 13))
        self.light3_2.setMaximumSize(QtCore.QSize(8, 13))
        self.light3_2.setStyleSheet("QLabel{\n"
"   border-style: outset;\n"
"    padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
"   \n"
" \n"
"  background-color:black;\n"
"}")
        self.light3_2.setText("")
        self.light3_2.setObjectName("light3_2")
        self.gridLayout.addWidget(self.light3_2, 0, 1, 1, 1,QtCore.Qt.AlignBottom)
        self.light3_3 = QtWidgets.QLabel(Form)
        self.light3_3.setMinimumSize(QtCore.QSize(8, 18))
        self.light3_3.setMaximumSize(QtCore.QSize(8, 18))
        self.light3_3.setStyleSheet("QLabel{\n"
"   border-style: outset;\n"
"  padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
" \n"
" \n"
"  background-color:black;\n"
"}")
        self.light3_3.setText("")
        self.light3_3.setObjectName("light3_3")
        self.gridLayout.addWidget(self.light3_3, 0, 2, 1, 1,QtCore.Qt.AlignBottom)
        self.light3_4 = QtWidgets.QLabel(Form)
        self.light3_4.setMinimumSize(QtCore.QSize(8, 23))
        self.light3_4.setMaximumSize(QtCore.QSize(8, 23))
        self.light3_4.setStyleSheet("QLabel{\n"
"   border-style: outset;\n"
"  padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
" \n"
" \n"
"  background-color:black;\n"
"}")
        self.light3_4.setText("")
        self.light3_4.setObjectName("light3_4")
        self.gridLayout.addWidget(self.light3_4, 0, 3, 1, 1,QtCore.Qt.AlignBottom)
        self.light3_5 = QtWidgets.QLabel(Form)
        self.light3_5.setMinimumSize(QtCore.QSize(8, 28))
        self.light3_5.setMaximumSize(QtCore.QSize(8, 28))
        self.light3_5.setStyleSheet("QLabel{\n"
"   border-style: outset;\n"
"    padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px; \n"
"  background-color:black;\n"
"}")
        self.light3_5.setText("")
        self.light3_5.setObjectName("light3_5")
        self.gridLayout.addWidget(self.light3_5, 0, 4, 1, 1,QtCore.Qt.AlignBottom)
        self.light3_6 = QtWidgets.QLabel(Form)
        self.light3_6.setMinimumSize(QtCore.QSize(8, 33))
        self.light3_6.setMaximumSize(QtCore.QSize(8, 33))
        self.light3_6.setStyleSheet("QLabel{\n"
"   border-style: outset;\n"
"   padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
" \n"
" \n"
"  background-color:black;\n"
"}")
        self.light3_6.setText("")
        self.light3_6.setObjectName("light3_6")
        self.gridLayout.addWidget(self.light3_6, 0, 5, 1, 1,QtCore.Qt.AlignBottom)
        self.light3_7 = QtWidgets.QLabel(Form)
        self.light3_7.setMinimumSize(QtCore.QSize(8, 38))
        self.light3_7.setMaximumSize(QtCore.QSize(8, 38))
        self.light3_7.setStyleSheet("QLabel{\n"
"   border-style: outset;\n"
"  padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
" \n"
"   \n"
"  background-color:black;\n"
"}")
        self.light3_7.setText("")
        self.light3_7.setObjectName("light3_7")
        self.gridLayout.addWidget(self.light3_7, 0, 6, 1, 1,QtCore.Qt.AlignBottom)
        self.light3_8 = QtWidgets.QLabel(Form)
        self.light3_8.setMinimumSize(QtCore.QSize(8, 43))
        self.light3_8.setMaximumSize(QtCore.QSize(8, 43))
        self.light3_8.setStyleSheet("QLabel{\n"
"  border-style: outset;\n"
"   padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
" \n"
" \n"
"  background-color:black;\n"
"}")
        self.light3_8.setText("")
        self.light3_8.setObjectName("light3_8")
        self.gridLayout.addWidget(self.light3_8, 0, 7, 1, 1,QtCore.Qt.AlignBottom)
        self.light3_9 = QtWidgets.QLabel(Form)
        self.light3_9.setMinimumSize(QtCore.QSize(8, 48))
        self.light3_9.setMaximumSize(QtCore.QSize(8, 48))
        self.light3_9.setStyleSheet("QLabel{\n"
"  border-style: outset;\n"
"  padding:2px;  \n"
"    border-radius:4px;\n"
"    \n"
"   border-width: 2px;\n"
" \n"
" \n"
"  background-color:black;\n"
"}")
        self.light3_9.setText("")
        self.light3_9.setObjectName("light3_9")
        self.gridLayout.addWidget(self.light3_9, 0, 8, 1, 1,QtCore.Qt.AlignBottom)
        self.light3_10 = QtWidgets.QLabel(Form)
        self.light3_10.setMinimumSize(QtCore.QSize(8, 53))
        self.light3_10.setMaximumSize(QtCore.QSize(8, 53))
        self.light3_10.setStyleSheet("QLabel{\n"
"  border-style: outset;\n"
"  padding:2px;  \n"
"    border-radius:4px;\n"
"    \n"
"   border-width: 2px;\n"
" \n"
" \n"
"  background-color:black;\n"
"}")
        self.light3_10.setText("")
        self.light3_10.setObjectName("light3_10")
        self.gridLayout.addWidget(self.light3_10, 0, 9, 1, 1,QtCore.Qt.AlignBottom)
        self.gridLayout_11.addLayout(self.gridLayout, 2, 3, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem19, 2, 4, 1, 1)
        self.light3Increment = QtWidgets.QToolButton(Form)
        self.light3Increment.setMinimumSize(QtCore.QSize(42, 42))
        self.light3Increment.setMaximumSize(QtCore.QSize(42, 42))
        self.light3Increment.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px; \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.light3Increment.setIcon(icon1)
        self.light3Increment.setObjectName("light3Increment")
        self.gridLayout_11.addWidget(self.light3Increment, 2, 5, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem20, 2, 6, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 1, 0, 2, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem21 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem21, 2, 0, 1, 1)
        self.lightLabel5 = QtWidgets.QLabel(Form)
        self.lightLabel5.setMinimumSize(QtCore.QSize(81, 19))
        self.lightLabel5.setMaximumSize(QtCore.QSize(81, 19))
        self.lightLabel5.setObjectName("lightLabel5")
        self.gridLayout_10.addWidget(self.lightLabel5, 0, 2, 1, 2)
        self.light4Decrement = QtWidgets.QToolButton(Form)
        self.light4Decrement.setMinimumSize(QtCore.QSize(42, 42))
        self.light4Decrement.setMaximumSize(QtCore.QSize(42, 42))
        self.light4Decrement.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px; \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.light4Decrement.setIcon(icon)
        self.light4Decrement.setObjectName("light4Decrement")
        self.gridLayout_10.addWidget(self.light4Decrement, 2, 1, 1, 1)
        self.light4Increment = QtWidgets.QToolButton(Form)
        self.light4Increment.setMinimumSize(QtCore.QSize(42, 42))
        self.light4Increment.setMaximumSize(QtCore.QSize(42, 42))
        self.light4Increment.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px; \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.light4Increment.setIcon(icon1)
        self.light4Increment.setObjectName("light4Increment")
        self.gridLayout_10.addWidget(self.light4Increment, 2, 5, 1, 1)
        self.lightBulb4 = QtWidgets.QLabel(Form)
        self.lightBulb4.setMinimumSize(QtCore.QSize(41, 41))
        self.lightBulb4.setMaximumSize(QtCore.QSize(41, 41))
        self.lightBulb4.setStyleSheet("QLabel { \n"
"color: #000000; \n"
"}")
        self.lightBulb4.setText("")
        self.lightBulb4.setPixmap(QtGui.QPixmap("icon/light-bulb.png"))
        self.lightBulb4.setScaledContents(True)
        self.lightBulb4.setObjectName("lightBulb4")
        self.gridLayout_10.addWidget(self.lightBulb4, 1, 1, 1, 2)
        self.toggleContainerLaminar = QtWidgets.QWidget(Form)
        self.toggleContainerLaminar.setMinimumSize(QtCore.QSize(111, 51))
        self.toggleContainerLaminar.setMaximumSize(QtCore.QSize(111, 51))
        self.toggleContainerLaminar.setObjectName("toggleContainerLaminar")
        self.gridLayout_10.addWidget(self.toggleContainerLaminar, 1, 3, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem22, 2, 2, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem23, 1, 5, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.light4_7 = QtWidgets.QLabel(Form)
        self.light4_7.setMinimumSize(QtCore.QSize(8, 38))
        self.light4_7.setMaximumSize(QtCore.QSize(8, 38))
        self.light4_7.setStyleSheet("QLabel{\n"
"   border-style: outset;\n"
"  padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
" \n"
"   \n"
"  background-color:black;\n"
"}")
        self.light4_7.setText("")
        self.light4_7.setObjectName("light4_7")
        self.gridLayout_9.addWidget(self.light4_7, 0, 6, 1, 1, QtCore.Qt.AlignBottom)
        self.light4_8 = QtWidgets.QLabel(Form)
        self.light4_8.setMinimumSize(QtCore.QSize(8, 43))
        self.light4_8.setMaximumSize(QtCore.QSize(8, 43))
        self.light4_8.setStyleSheet("QLabel{\n"
"  border-style: outset;\n"
"   padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
" \n"
" \n"
"  background-color:black;\n"
"}")
        self.light4_8.setText("")
        self.light4_8.setObjectName("light4_8")
        self.gridLayout_9.addWidget(self.light4_8, 0, 7, 1, 1,QtCore.Qt.AlignBottom)
        self.light4_10 = QtWidgets.QLabel(Form)
        self.light4_10.setMinimumSize(QtCore.QSize(8, 53))
        self.light4_10.setMaximumSize(QtCore.QSize(8, 53))
        self.light4_10.setStyleSheet("QLabel{\n"
"  border-style: outset;\n"
"  padding:2px;  \n"
"    border-radius:4px;\n"
"    \n"
"   border-width: 2px;\n"
" \n"
" \n"
"  background-color:black;\n"
"}")
        self.light4_10.setText("")
        self.light4_10.setObjectName("light4_10")
        self.gridLayout_9.addWidget(self.light4_10, 0, 9, 1, 1,QtCore.Qt.AlignBottom)
        self.light4_3 = QtWidgets.QLabel(Form)
        self.light4_3.setMinimumSize(QtCore.QSize(8, 18))
        self.light4_3.setMaximumSize(QtCore.QSize(8, 18))
        self.light4_3.setStyleSheet("QLabel{\n"
"   border-style: outset;\n"
"  padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
" \n"
" \n"
"  background-color:black;\n"
"}")
        self.light4_3.setText("")
        self.light4_3.setObjectName("light4_3")
        self.gridLayout_9.addWidget(self.light4_3, 0, 2, 1, 1,QtCore.Qt.AlignBottom)
        self.light4_6 = QtWidgets.QLabel(Form)
        self.light4_6.setMinimumSize(QtCore.QSize(8, 33))
        self.light4_6.setMaximumSize(QtCore.QSize(8, 33))
        self.light4_6.setStyleSheet("QLabel{\n"
"   border-style: outset;\n"
"   padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
" \n"
" \n"
"  background-color:black;\n"
"}")
        self.light4_6.setText("")
        self.light4_6.setObjectName("light4_6")
        self.gridLayout_9.addWidget(self.light4_6, 0, 5, 1, 1,QtCore.Qt.AlignBottom)
        self.light4_9 = QtWidgets.QLabel(Form)
        self.light4_9.setMinimumSize(QtCore.QSize(8, 48))
        self.light4_9.setMaximumSize(QtCore.QSize(8, 48))
        self.light4_9.setStyleSheet("QLabel{\n"
"  border-style: outset;\n"
"  padding:2px;  \n"
"    border-radius:4px;\n"
"    \n"
"   border-width: 2px;\n"
" \n"
" \n"
"  background-color:black;\n"
"}")
        self.light4_9.setText("")
        self.light4_9.setObjectName("light4_9")
        self.gridLayout_9.addWidget(self.light4_9, 0, 8, 1, 1,QtCore.Qt.AlignBottom)
        self.light4_2 = QtWidgets.QLabel(Form)
        self.light4_2.setMinimumSize(QtCore.QSize(8, 13))
        self.light4_2.setMaximumSize(QtCore.QSize(8, 13))
        self.light4_2.setStyleSheet("QLabel{\n"
"   border-style: outset;\n"
"    padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
"   \n"
" \n"
"  background-color:black;\n"
"}")
        self.light4_2.setText("")
        self.light4_2.setObjectName("light4_2")
        self.gridLayout_9.addWidget(self.light4_2, 0, 1, 1, 1,QtCore.Qt.AlignBottom)
        self.light4_5 = QtWidgets.QLabel(Form)
        self.light4_5.setMinimumSize(QtCore.QSize(8, 28))
        self.light4_5.setMaximumSize(QtCore.QSize(8, 28))
        self.light4_5.setStyleSheet("QLabel{\n"
"   border-style: outset;\n"
"    padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px; \n"
"  background-color:black;\n"
"}")
        self.light4_5.setText("")
        self.light4_5.setObjectName("light4_5")
        self.gridLayout_9.addWidget(self.light4_5, 0, 4, 1, 1,QtCore.Qt.AlignBottom)
        self.light4_4 = QtWidgets.QLabel(Form)
        self.light4_4.setMinimumSize(QtCore.QSize(8, 23))
        self.light4_4.setMaximumSize(QtCore.QSize(8, 23))
        self.light4_4.setStyleSheet("QLabel{\n"
"   border-style: outset;\n"
"  padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
" \n"
" \n"
"  background-color:black;\n"
"}")
        self.light4_4.setText("")
        self.light4_4.setObjectName("light4_4")
        self.gridLayout_9.addWidget(self.light4_4, 0, 3, 1, 1,QtCore.Qt.AlignBottom)
        self.light4_1 = QtWidgets.QLabel(Form)
        self.light4_1.setEnabled(True)
        self.light4_1.setMinimumSize(QtCore.QSize(8, 8))
        self.light4_1.setMaximumSize(QtCore.QSize(8, 8))
        self.light4_1.setStyleSheet("QLabel{\n"
" border-style: outset;\n"
"    padding:2px;  \n"
"    border-radius:4px;\n"
"  border-width: 2px;\n"
"   \n"
"  background-color:black;\n"
"}")
        self.light4_1.setText("")
        self.light4_1.setObjectName("light4_1")
        self.gridLayout_9.addWidget(self.light4_1, 0, 0, 1, 1,QtCore.Qt.AlignBottom)
        self.gridLayout_10.addLayout(self.gridLayout_9, 2, 3, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem24, 2, 4, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem25, 2, 6, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem26, 1, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_10, 1, 1, 2, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.toggleContainerOT2 = QtWidgets.QWidget(Form)
        self.toggleContainerOT2.setMinimumSize(QtCore.QSize(111, 51))
        self.toggleContainerOT2.setMaximumSize(QtCore.QSize(111, 51))
        self.toggleContainerOT2.setObjectName("toggleContainerOT2")
        self.gridLayout_7.addWidget(self.toggleContainerOT2, 1, 1, 1, 1, QtCore.Qt.AlignTop)
        self.otLightBulb2 = QtWidgets.QLabel(Form)
        self.otLightBulb2.setMinimumSize(QtCore.QSize(31, 31))
        self.otLightBulb2.setMaximumSize(QtCore.QSize(31, 31))
        self.otLightBulb2.setStyleSheet("QLabel { \n"
"color: #000000; \n"
"}")
        self.otLightBulb2.setText("")
        self.otLightBulb2.setPixmap(QtGui.QPixmap("icon/lights.png"))
        self.otLightBulb2.setScaledContents(True)
        self.otLightBulb2.setObjectName("otLightBulb2")
        self.gridLayout_7.addWidget(self.otLightBulb2, 1, 0, 1, 1)
        self.lightLabel6 = QtWidgets.QLabel(Form)
        self.lightLabel6.setMinimumSize(QtCore.QSize(67, 19))
        self.lightLabel6.setMaximumSize(QtCore.QSize(67, 19))
        self.lightLabel6.setObjectName("lightLabel6")
        self.gridLayout_7.addWidget(self.lightLabel6, 0, 1, 1, 1, QtCore.Qt.AlignTop)
        self.gridLayout_12.addLayout(self.gridLayout_7, 1, 2, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem27, 2, 2, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_12, 2, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setMinimumSize(QtCore.QSize(581, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_14.addWidget(self.line_2, 3, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.toggleContainerGasL2.raise_()
        self.light3_6.raise_()
        self.light3_7.raise_()
        self.light3_9.raise_()
        self.light3_3.raise_()
        self.light3_2.raise_()
        self.light3_5.raise_()
        self.light3_8.raise_()
        self.light3_1.raise_()
        self.light3_10.raise_()
        self.light3_4.raise_()
        self.light4_9.raise_()
        self.light4_1.raise_()
        self.light4_3.raise_()
        self.light4_7.raise_()
        self.light4_5.raise_()
        self.light4_8.raise_()
        self.light4_6.raise_()
        self.light4_10.raise_()
        self.light4_4.raise_()
        self.light4_2.raise_()
        self.light1Decrement.raise_()
        self.light1Increment.raise_()
        self.light3Increment.raise_()
        self.light4Decrement.raise_()
        self.light3Decrement.raise_()
        self.light4Increment.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.lightLabel4.raise_()
        self.lightBulb3.raise_()
        self.toggleContainer.raise_()
        self.lightLabel5.raise_()
        self.lightBulb4.raise_()
        self.toggleContainerLaminar.raise_()
        self.lightLabel2.raise_()
        self.lightBulb2.raise_()
        self.lightLabel1.raise_()
        self.toggleContainerGasL1.raise_()
        self.lightBulb1.raise_()
        self.light1_3.raise_()
        self.light1_6.raise_()
        self.light1_10.raise_()
        self.light1_8.raise_()
        self.light1_5.raise_()
        self.light1_2.raise_()
        self.light1_7.raise_()
        self.light1_1.raise_()
        self.light1_9.raise_()
        self.light1_4.raise_()
        self.light2Increment.raise_()
        self.light2Decrement.raise_()
        self.light2_9.raise_()
        self.light2_7.raise_()
        self.light2_4.raise_()
        self.light2_10.raise_()
        self.light2_5.raise_()
        self.light2_8.raise_()
        self.light2_6.raise_()
        self.light2_2.raise_()
        self.light2_3.raise_()
        self.light2_1.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lightLabel1.setText(_translate("Form", "Gen Light - 1"))
        self.light1Decrement.setText(_translate("Form", "..."))
        self.light1Increment.setText(_translate("Form", "..."))
        self.lightLabel2.setText(_translate("Form", "Gen Light - 2"))
        self.light2Decrement.setText(_translate("Form", "..."))
        self.light2Increment.setText(_translate("Form", "..."))
        self.lightLabel3.setText(_translate("Form", "OT 1"))
        self.lightLabel4.setText(_translate("Form", "Peripheral"))
        self.light3Decrement.setText(_translate("Form", "..."))
        self.light3Increment.setText(_translate("Form", "..."))
        self.lightLabel5.setText(_translate("Form", "Laminar"))
        self.light4Decrement.setText(_translate("Form", "..."))
        self.light4Increment.setText(_translate("Form", "..."))
        self.lightLabel6.setText(_translate("Form", "OT 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
