# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setClockDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setClockTime(object):
    def setupUi(self, setClockTime):
        setClockTime.setObjectName("setClockTime")
        setClockTime.resize(535, 340)
        setClockTime.setStyleSheet("QDialog{\n"
"background-color: #000000;\n"
"}")
        self.buttonClockBox = QtWidgets.QDialogButtonBox(setClockTime)
        self.buttonClockBox.setGeometry(QtCore.QRect(120, 220, 211, 61))
        self.buttonClockBox.setStyleSheet("QDialogButtonBox{\n"
" color: #FFFFFF;\n"
"}")
        self.buttonClockBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonClockBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonClockBox.setObjectName("buttonClockBox")
        self.timeEdit = QtWidgets.QTimeEdit(setClockTime)
        self.timeEdit.setGeometry(QtCore.QRect(230, 110, 111, 31))
        self.timeEdit.setStyleSheet("QTimeEdit{\n"
" color: #FFFFFF;\n"
"}")
        self.timeEdit.setObjectName("timeEdit")
        self.dateEdit = QtWidgets.QDateEdit(setClockTime)
        self.dateEdit.setGeometry(QtCore.QRect(230, 60, 110, 31))
        self.dateEdit.setStyleSheet("QTimeEdit{\n"
" color: #FFFFFF;\n"
"}")
        self.dateEdit.setObjectName("dateEdit")
        self.label = QtWidgets.QLabel(setClockTime)
        self.label.setGeometry(QtCore.QRect(160, 70, 41, 21))
        self.label.setStyleSheet("QLabel{\n"
" color: #FFFFFF;\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(setClockTime)
        self.label_2.setGeometry(QtCore.QRect(160, 120, 41, 21))
        self.label_2.setStyleSheet("QLabel{\n"
" color: #FFFFFF;\n"
"}")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(setClockTime)
        self.buttonClockBox.accepted.connect(setClockTime.accept)
        self.buttonClockBox.rejected.connect(setClockTime.reject)
        QtCore.QMetaObject.connectSlotsByName(setClockTime)

    def retranslateUi(self, setClockTime):
        _translate = QtCore.QCoreApplication.translate
        setClockTime.setWindowTitle(_translate("setClockTime", "Clock Settings"))
        self.label.setText(_translate("setClockTime", "Date:"))
        self.label_2.setText(_translate("setClockTime", "Time:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    setClockTime = QtWidgets.QDialog()
    ui = Ui_setClockTime()
    ui.setupUi(setClockTime)
    setClockTime.show()
    sys.exit(app.exec_())
