# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setClockDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setClockTime(object):
    def setupUi(self, setClockTime):
        setClockTime.setObjectName("setClockTime")
        setClockTime.resize(535, 340)
        setClockTime.setStyleSheet("QDialog{\n"
"background-color: #000000;\n"
"}")
        self.timeEdit = QtWidgets.QTimeEdit(setClockTime)
        self.timeEdit.setGeometry(QtCore.QRect(230, 110, 181, 42))
        self.timeEdit.setStyleSheet("QTimeEdit::up-button { width: 48px; }\n"
"QTimeEdit::down-button { width: 48px; }")
        self.timeEdit.setObjectName("timeEdit")
        self.dateEdit = QtWidgets.QDateEdit(setClockTime)
        self.dateEdit.setGeometry(QtCore.QRect(230, 60, 181, 42))
        self.dateEdit.setStyleSheet("QDateEdit::up-button { width: 48px; }\n"
"QDateEdit::down-button { width: 48px; }")
        self.dateEdit.setObjectName("dateEdit")
        self.label = QtWidgets.QLabel(setClockTime)
        self.label.setGeometry(QtCore.QRect(160, 70, 41, 21))
        self.label.setStyleSheet("QLabel{\n"
" color: #FFFFFF;\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(setClockTime)
        self.label_2.setGeometry(QtCore.QRect(160, 120, 41, 21))
        self.label_2.setStyleSheet("QLabel{\n"
" color: #FFFFFF;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.buttonClockOk = QtWidgets.QPushButton(setClockTime)
        self.buttonClockOk.setGeometry(QtCore.QRect(310, 220, 100, 42))
        self.buttonClockOk.setStyleSheet("QPushButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.buttonClockOk.setObjectName("buttonClockOk")
        self.buttonClockCancel = QtWidgets.QPushButton(setClockTime)
        self.buttonClockCancel.setGeometry(QtCore.QRect(200, 220, 100, 42))
        self.buttonClockCancel.setStyleSheet("QPushButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.buttonClockCancel.setObjectName("buttonClockCancel")

        self.retranslateUi(setClockTime)
        QtCore.QMetaObject.connectSlotsByName(setClockTime)

    def retranslateUi(self, setClockTime):
        _translate = QtCore.QCoreApplication.translate
        setClockTime.setWindowTitle(_translate("setClockTime", "Clock Settings"))
        self.label.setText(_translate("setClockTime", "Date:"))
        self.label_2.setText(_translate("setClockTime", "Time:"))
        self.buttonClockOk.setText(_translate("setClockTime", "Ok"))
        self.buttonClockCancel.setText(_translate("setClockTime", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    setClockTime = QtWidgets.QDialog()
    ui = Ui_setClockTime()
    ui.setupUi(setClockTime)
    setClockTime.show()
    sys.exit(app.exec_())
