# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setTimerDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setTimer(object):
    def setupUi(self, setTimer):
        setTimer.setObjectName("setTimer")
        setTimer.resize(535, 340)
        setTimer.setStyleSheet(" QDialog{\n"
"background-color:#000000;\n"
"}")
        setTimer.setSizeGripEnabled(False)
        setTimer.setModal(False)
        self.hourSlider = QtWidgets.QSlider(setTimer)
        self.hourSlider.setGeometry(QtCore.QRect(120, 140, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.hourSlider.setFont(font)
        self.hourSlider.setStyleSheet("")
        self.hourSlider.setMaximum(99)
        self.hourSlider.setSingleStep(1)
        self.hourSlider.setProperty("value", 99)
        self.hourSlider.setOrientation(QtCore.Qt.Horizontal)
        self.hourSlider.setObjectName("hourSlider")
        self.minuteSlider = QtWidgets.QSlider(setTimer)
        self.minuteSlider.setGeometry(QtCore.QRect(120, 190, 371, 51))
        self.minuteSlider.setStyleSheet("")
        self.minuteSlider.setMaximum(59)
        self.minuteSlider.setSingleStep(1)
        self.minuteSlider.setProperty("value", 59)
        self.minuteSlider.setOrientation(QtCore.Qt.Horizontal)
        self.minuteSlider.setObjectName("minuteSlider")
        self.secondSlider = QtWidgets.QSlider(setTimer)
        self.secondSlider.setGeometry(QtCore.QRect(120, 240, 371, 51))
        self.secondSlider.setStyleSheet("")
        self.secondSlider.setMaximum(59)
        self.secondSlider.setSingleStep(1)
        self.secondSlider.setProperty("value", 59)
        self.secondSlider.setOrientation(QtCore.Qt.Horizontal)
        self.secondSlider.setObjectName("secondSlider")
        self.spinSecondBox = QtWidgets.QSpinBox(setTimer)
        self.spinSecondBox.setGeometry(QtCore.QRect(370, 30, 131, 91))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spinSecondBox.setFont(font)
        self.spinSecondBox.setStyleSheet("QSpinBox::up-button { width: 48px; }\n"
"QSpinBox::down-button { width: 48px; }\n"
"QSpinBox{\n"
"font:51px;\n"
"}\n"
"")
        self.spinSecondBox.setMaximum(59)
        self.spinSecondBox.setProperty("value", 59)
        self.spinSecondBox.setObjectName("spinSecondBox")
        self.spinMinuteBox = QtWidgets.QSpinBox(setTimer)
        self.spinMinuteBox.setGeometry(QtCore.QRect(210, 30, 131, 91))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(40)
        self.spinMinuteBox.setFont(font)
        self.spinMinuteBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.spinMinuteBox.setStyleSheet("QSpinBox::up-button { width: 48px; }\n"
"QSpinBox::down-button { width: 48px; }\n"
"")
        self.spinMinuteBox.setMaximum(59)
        self.spinMinuteBox.setProperty("value", 59)
        self.spinMinuteBox.setObjectName("spinMinuteBox")
        self.spinHourBox = QtWidgets.QSpinBox(setTimer)
        self.spinHourBox.setGeometry(QtCore.QRect(40, 30, 131, 91))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(36)
        self.spinHourBox.setFont(font)
        self.spinHourBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.spinHourBox.setStyleSheet("QSpinBox::up-button { width: 48px; }\n"
"QSpinBox::down-button { width: 48px; }\n"
" \n"
"")
        self.spinHourBox.setMaximum(99)
        self.spinHourBox.setProperty("value", 99)
        self.spinHourBox.setObjectName("spinHourBox")
        self.secondL = QtWidgets.QLabel(setTimer)
        self.secondL.setGeometry(QtCore.QRect(50, 240, 59, 28))
        self.secondL.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.secondL.setObjectName("secondL")
        self.minuteL = QtWidgets.QLabel(setTimer)
        self.minuteL.setGeometry(QtCore.QRect(50, 190, 51, 45))
        self.minuteL.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.minuteL.setObjectName("minuteL")
        self.hourL = QtWidgets.QLabel(setTimer)
        self.hourL.setGeometry(QtCore.QRect(50, 150, 41, 31))
        self.hourL.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.hourL.setObjectName("hourL")
        self.hourT = QtWidgets.QLabel(setTimer)
        self.hourT.setGeometry(QtCore.QRect(70, 0, 41, 31))
        self.hourT.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.hourT.setObjectName("hourT")
        self.minuteT = QtWidgets.QLabel(setTimer)
        self.minuteT.setGeometry(QtCore.QRect(250, 0, 51, 21))
        self.minuteT.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.minuteT.setObjectName("minuteT")
        self.secondT = QtWidgets.QLabel(setTimer)
        self.secondT.setGeometry(QtCore.QRect(400, 0, 59, 21))
        self.secondT.setStyleSheet("QLabel{\n"
"color:#FFFFFF;\n"
"}")
        self.secondT.setObjectName("secondT")
        self.buttonOk = QtWidgets.QPushButton(setTimer)
        self.buttonOk.setGeometry(QtCore.QRect(400, 290, 100, 31))
        self.buttonOk.setStyleSheet("QPushButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QPushButton#pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.buttonOk.setObjectName("buttonOk")
        self.buttonCancel = QtWidgets.QPushButton(setTimer)
        self.buttonCancel.setGeometry(QtCore.QRect(296, 290, 100, 31))
        self.buttonCancel.setStyleSheet("QPushButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#FFFFFF;\n"
"}\n"
"QPushButton#pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.buttonCancel.setObjectName("buttonCancel")

        self.retranslateUi(setTimer)
        QtCore.QMetaObject.connectSlotsByName(setTimer)

    def retranslateUi(self, setTimer):
        _translate = QtCore.QCoreApplication.translate
        setTimer.setWindowTitle(_translate("setTimer", "Timer Setting"))
        self.secondL.setText(_translate("setTimer", "Second"))
        self.minuteL.setText(_translate("setTimer", "Minute"))
        self.hourL.setText(_translate("setTimer", "Hour"))
        self.hourT.setText(_translate("setTimer", "Hour"))
        self.minuteT.setText(_translate("setTimer", "Minute"))
        self.secondT.setText(_translate("setTimer", "Second"))
        self.buttonOk.setText(_translate("setTimer", "Ok"))
        self.buttonCancel.setText(_translate("setTimer", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    setTimer = QtWidgets.QDialog()
    ui = Ui_setTimer()
    ui.setupUi(setTimer)
    setTimer.show()
    sys.exit(app.exec_())
