# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shutDownDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_shutDownDialog(object):
    def setupUi(self, shutDownDialog):
        shutDownDialog.setObjectName("shutDownDialog")
        shutDownDialog.resize(313, 290)
        self.gridLayout = QtWidgets.QGridLayout(shutDownDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.shutDownButton = QtWidgets.QPushButton(shutDownDialog)
        self.shutDownButton.setMinimumSize(QtCore.QSize(293, 61))
        self.shutDownButton.setObjectName("shutDownButton")
        self.verticalLayout.addWidget(self.shutDownButton)
        self.rebootButton = QtWidgets.QPushButton(shutDownDialog)
        self.rebootButton.setMinimumSize(QtCore.QSize(293, 61))
        self.rebootButton.setObjectName("rebootButton")
        self.verticalLayout.addWidget(self.rebootButton)
        self.logoutButton = QtWidgets.QPushButton(shutDownDialog)
        self.logoutButton.setMinimumSize(QtCore.QSize(293, 61))
        self.logoutButton.setObjectName("logoutButton")
        self.verticalLayout.addWidget(self.logoutButton)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.cancelShutButton = QtWidgets.QPushButton(shutDownDialog)
        self.cancelShutButton.setMinimumSize(QtCore.QSize(295, 31))
        self.cancelShutButton.setObjectName("cancelShutButton")
        self.gridLayout.addWidget(self.cancelShutButton, 1, 0, 1, 1)

        self.retranslateUi(shutDownDialog)
        QtCore.QMetaObject.connectSlotsByName(shutDownDialog)

    def retranslateUi(self, shutDownDialog):
        _translate = QtCore.QCoreApplication.translate
        shutDownDialog.setWindowTitle(_translate("shutDownDialog", "Dialog"))
        self.shutDownButton.setText(_translate("shutDownDialog", "Shutdown"))
        self.rebootButton.setText(_translate("shutDownDialog", "Reboot"))
        self.logoutButton.setText(_translate("shutDownDialog", "Suspend"))
        self.cancelShutButton.setText(_translate("shutDownDialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    shutDownDialog = QtWidgets.QDialog()
    ui = Ui_shutDownDialog()
    ui.setupUi(shutDownDialog)
    shutDownDialog.show()
    sys.exit(app.exec_())
