# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telephonepad.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_telephonePad(object):
    def setupUi(self, telephonePad):
        telephonePad.setObjectName("telephonePad")
        telephonePad.resize(339, 424)
        self.gridLayout = QtWidgets.QGridLayout(telephonePad)
        self.gridLayout.setObjectName("gridLayout")
        self.lcdNumber = QtWidgets.QLineEdit(telephonePad)
        self.lcdNumber.setStyleSheet("QLineEdit {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 47px;\n"
"    \n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#1976D2;\n"
"   \n"
"}\n"
"QLineEdit:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 0, 0, 1, 3)
        self.button1 = QtWidgets.QToolButton(telephonePad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button1.sizePolicy().hasHeightForWidth())
        self.button1.setSizePolicy(sizePolicy)
        self.button1.setMinimumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button1.setFont(font)
        self.button1.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 47px;\n"
"    width:51;\n"
"    hieght:51;\n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#1976D2;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.button1.setObjectName("button1")
        self.gridLayout.addWidget(self.button1, 1, 0, 1, 1)
        self.button2 = QtWidgets.QToolButton(telephonePad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button2.sizePolicy().hasHeightForWidth())
        self.button2.setSizePolicy(sizePolicy)
        self.button2.setMinimumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button2.setFont(font)
        self.button2.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 47px;\n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#1976D2;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.button2.setObjectName("button2")
        self.gridLayout.addWidget(self.button2, 1, 1, 1, 1)
        self.button3 = QtWidgets.QToolButton(telephonePad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button3.sizePolicy().hasHeightForWidth())
        self.button3.setSizePolicy(sizePolicy)
        self.button3.setMinimumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button3.setFont(font)
        self.button3.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 47px;\n"
"    \n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#1976D2;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.button3.setObjectName("button3")
        self.gridLayout.addWidget(self.button3, 1, 2, 1, 1)
        self.button4 = QtWidgets.QToolButton(telephonePad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button4.sizePolicy().hasHeightForWidth())
        self.button4.setSizePolicy(sizePolicy)
        self.button4.setMinimumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button4.setFont(font)
        self.button4.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 47px;\n"
"    \n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#1976D2;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.button4.setObjectName("button4")
        self.gridLayout.addWidget(self.button4, 2, 0, 1, 1)
        self.button5 = QtWidgets.QToolButton(telephonePad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button5.sizePolicy().hasHeightForWidth())
        self.button5.setSizePolicy(sizePolicy)
        self.button5.setMinimumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button5.setFont(font)
        self.button5.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 47px;\n"
"    \n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#1976D2;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.button5.setObjectName("button5")
        self.gridLayout.addWidget(self.button5, 2, 1, 1, 1)
        self.button6 = QtWidgets.QToolButton(telephonePad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button6.sizePolicy().hasHeightForWidth())
        self.button6.setSizePolicy(sizePolicy)
        self.button6.setMinimumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button6.setFont(font)
        self.button6.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 47px;\n"
"    \n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#1976D2;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.button6.setObjectName("button6")
        self.gridLayout.addWidget(self.button6, 2, 2, 1, 1)
        self.button7 = QtWidgets.QToolButton(telephonePad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button7.sizePolicy().hasHeightForWidth())
        self.button7.setSizePolicy(sizePolicy)
        self.button7.setMinimumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button7.setFont(font)
        self.button7.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 47px;\n"
"    \n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#1976D2;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.button7.setObjectName("button7")
        self.gridLayout.addWidget(self.button7, 3, 0, 1, 1)
        self.button8 = QtWidgets.QToolButton(telephonePad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button8.sizePolicy().hasHeightForWidth())
        self.button8.setSizePolicy(sizePolicy)
        self.button8.setMinimumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button8.setFont(font)
        self.button8.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 47px;\n"
"    \n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#1976D2;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.button8.setObjectName("button8")
        self.gridLayout.addWidget(self.button8, 3, 1, 1, 1)
        self.button9 = QtWidgets.QToolButton(telephonePad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button9.sizePolicy().hasHeightForWidth())
        self.button9.setSizePolicy(sizePolicy)
        self.button9.setMinimumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button9.setFont(font)
        self.button9.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 47px;\n"
"    \n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#1976D2;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.button9.setObjectName("button9")
        self.gridLayout.addWidget(self.button9, 3, 2, 1, 1)
        self.button10 = QtWidgets.QToolButton(telephonePad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button10.sizePolicy().hasHeightForWidth())
        self.button10.setSizePolicy(sizePolicy)
        self.button10.setMinimumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button10.setFont(font)
        self.button10.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 47px;\n"
"    \n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#1976D2;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.button10.setObjectName("button10")
        self.gridLayout.addWidget(self.button10, 4, 0, 1, 1)
        self.button0 = QtWidgets.QToolButton(telephonePad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button0.sizePolicy().hasHeightForWidth())
        self.button0.setSizePolicy(sizePolicy)
        self.button0.setMinimumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button0.setFont(font)
        self.button0.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 47px;\n"
"    \n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#1976D2;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.button0.setObjectName("button0")
        self.gridLayout.addWidget(self.button0, 4, 1, 1, 1)
        self.button11 = QtWidgets.QToolButton(telephonePad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button11.sizePolicy().hasHeightForWidth())
        self.button11.setSizePolicy(sizePolicy)
        self.button11.setMinimumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button11.setFont(font)
        self.button11.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 47px;\n"
"    \n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#1976D2;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.button11.setObjectName("button11")
        self.gridLayout.addWidget(self.button11, 4, 2, 1, 1)
        self.buttonClear = QtWidgets.QToolButton(telephonePad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonClear.sizePolicy().hasHeightForWidth())
        self.buttonClear.setSizePolicy(sizePolicy)
        self.buttonClear.setMinimumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.buttonClear.setFont(font)
        self.buttonClear.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 47px;\n"
"    \n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#1976D2;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/backspace-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonClear.setIcon(icon)
        self.buttonClear.setIconSize(QtCore.QSize(47, 47))
        self.buttonClear.setObjectName("buttonClear")
        self.gridLayout.addWidget(self.buttonClear, 5, 0, 1, 1)
        self.buttonCall = QtWidgets.QToolButton(telephonePad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonCall.sizePolicy().hasHeightForWidth())
        self.buttonCall.setSizePolicy(sizePolicy)
        self.buttonCall.setMinimumSize(QtCore.QSize(111, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.buttonCall.setFont(font)
        self.buttonCall.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 47px;\n"
"    \n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#1976D2;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.buttonCall.setObjectName("buttonCall")
        self.gridLayout.addWidget(self.buttonCall, 5, 1, 1, 2)
        self.closeTelephonePad = QtWidgets.QToolButton(telephonePad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeTelephonePad.sizePolicy().hasHeightForWidth())
        self.closeTelephonePad.setSizePolicy(sizePolicy)
        self.closeTelephonePad.setMinimumSize(QtCore.QSize(321, 41))
        self.closeTelephonePad.setStyleSheet("QToolButton {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 24px;\n"
"    \n"
"     \n"
"    padding: 6px;\n"
"    background-color: #000000;\n"
"    color:#1976D2;\n"
"   \n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.closeTelephonePad.setObjectName("closeTelephonePad")
        self.gridLayout.addWidget(self.closeTelephonePad, 6, 0, 1, 3)
        self.closeTelephonePad.raise_()

        self.retranslateUi(telephonePad)
        QtCore.QMetaObject.connectSlotsByName(telephonePad)

    def retranslateUi(self, telephonePad):
        _translate = QtCore.QCoreApplication.translate
        telephonePad.setWindowTitle(_translate("telephonePad", "Telephone Pad"))
        self.button1.setText(_translate("telephonePad", "1"))
        self.button2.setText(_translate("telephonePad", "2"))
        self.button3.setText(_translate("telephonePad", "3"))
        self.button4.setText(_translate("telephonePad", "4"))
        self.button5.setText(_translate("telephonePad", "5"))
        self.button6.setText(_translate("telephonePad", "6"))
        self.button7.setText(_translate("telephonePad", "7"))
        self.button8.setText(_translate("telephonePad", "8"))
        self.button9.setText(_translate("telephonePad", "9"))
        self.button10.setText(_translate("telephonePad", "#"))
        self.button0.setText(_translate("telephonePad", "0"))
        self.button11.setText(_translate("telephonePad", "+"))
        self.buttonClear.setText(_translate("telephonePad", "AC"))
        self.buttonCall.setText(_translate("telephonePad", "Call"))
        self.closeTelephonePad.setText(_translate("telephonePad", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    telephonePad = QtWidgets.QDialog()
    ui = Ui_telephonePad()
    ui.setupUi(telephonePad)
    telephonePad.show()
    sys.exit(app.exec_())
