# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventilationDetails.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventilationDetails(object):
    def setupUi(self, ventilationDetails):
        ventilationDetails.setObjectName("ventilationDetails")
        ventilationDetails.resize(640, 480)
        self.toolButton = QtWidgets.QToolButton(ventilationDetails)
        self.toolButton.setGeometry(QtCore.QRect(180, 140, 151, 71))
        self.toolButton.setObjectName("toolButton")
        self.line = QtWidgets.QFrame(ventilationDetails)
        self.line.setGeometry(QtCore.QRect(270, 310, 118, 3))
        self.line.setStyleSheet("Line{border-radius: 25px;\n"
"  background: #73AD21;\n"
"  padding: 20px; \n"
"  width: 200px;\n"
"  height: 150px;  }")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(ventilationDetails)
        QtCore.QMetaObject.connectSlotsByName(ventilationDetails)

    def retranslateUi(self, ventilationDetails):
        _translate = QtCore.QCoreApplication.translate
        ventilationDetails.setWindowTitle(_translate("ventilationDetails", "Ventilation"))
        self.toolButton.setText(_translate("ventilationDetails", "Tool"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventilationDetails = QtWidgets.QWidget()
    ui = Ui_ventilationDetails()
    ui.setupUi(ventilationDetails)
    ventilationDetails.show()
    sys.exit(app.exec_())
